### ISSUE TITLE
m3u playlist saves with every line as the first video

### ISSUE THREAD

**Issue by jdsutherland** [donmaiq/Mpv-Playlistmanager#1]
Upon saving the playlist, every line in the m3u file is the first video of the playlist. I've tried moving the current playing file around to various positions (e.g. last file) but this didn't change anything.

I'm on OSX 10.11.

**Comment by jonniek** [comment]
Thanks for the issue. I had some variables outside of the loop so it saved the first one every time. It is fixed now.

**Comment by jdsutherland** [comment]
@jonniek Cheers. Thanks for making an awesome plugin.
