### ISSUE TITLE
updating playlist rather than creating a new .m3u file

### ISSUE THREAD

**Issue by doesn123** [donmaiq/Mpv-Playlistmanager#100]
Is it possible to make changes to a playlist and then to update that m3u file? At the moment I have to instead save the updated playlist and then rename it to overwrite the previous version of the playlist

**Comment by jonniek** [comment]
Are you using [playlistmanager-save-interactive.lua](https://github.com/jonniek/mpv-playlistmanager/blob/master/playlistmanager-save-interactive.lua)?

**Comment by doesn123** [comment]
No I’m not

**Comment by jonniek** [comment]
With that it will be easier to overwrite a playlist as it prompts you for a filename when you save playlist, if you add existing name it will overwrite.
