### ISSUE TITLE
Playlist is overflowing mpv window

### ISSUE THREAD

**Issue by nobef** [donmaiq/Mpv-Playlistmanager#106]
I don't see what I'm choosing after 11 lines. I hope you got what I meant

**Comment by jonniek** [comment]
Try adjusting some of the following values in the settings
```lua
showamount = 10,
style_ass_tags = "{\\fs10}",

scale_playlist_by_window=true, -- Note: this is maybe broken right now and not have an effect
```

I think showamount 10 should do fix it for you.

**Comment by nobef** [comment]
@jonniek All is well, thank you!
 I hope there are fixes here.

**Comment by jonniek** [comment]
It could be better and know the size automatically. I'll leave the issue open for that. It should probably be possible to have it calculate available size.

**Comment by ma-zsola** [comment]
> It could be better and know the size automatically. I'll leave the issue open for that. It should probably be possible to have it calculate available size.

The max osd lines can be calculated if we know the osd height and the font size (osd height/font size). But it doesn't include the libass linebreaks. In this case a scrollbar might be useful, but I think it's hard to implement.
