### ISSUE TITLE
Add a 'seconds' value to show playlist

### ISSUE THREAD

**Issue by indeedwatson** [donmaiq/Mpv-Playlistmanager#11]
I'd like to use a single keybind to go back or forth in the playlist and show the playlist, but have the playlist hide itself after a few seconds.

**Comment by jonniek** [comment]
https://github.com/jonniek/mpv-playlistmanager/blob/f171a9efbad163889c306a5fe2029231b7374095/playlistmanager.conf#L41-L42

Set this as no

https://github.com/jonniek/mpv-playlistmanager/blob/f171a9efbad163889c306a5fe2029231b7374095/playlistmanager.conf#L52-L53

Set this as your preferred timeout in seconds

Optionally you can edit the settings in the lua file inside the settings variable.

If the above didn't answer your question do you perhaps need to show the playlist independent of it's default behavior? At the moment that is not possible but if you need it I can add that feature as a script-message.

**Comment by indeedwatson** [comment]
Thanks, that worked. What's odd is that no matter what number I put as the timeout, it always takes about 10 seconds to disappear. This isn't a huge issue, but it's weird.

**Comment by jonniek** [comment]
I just fixed some bugs with the playlist visibility when selecting a file and some timer tweaks. Set the default timeout to 5 seconds as well.

I'm not sure why it takes 10 seconds to disappear for you. If you edited the lua directly are you sure you don't have a `playlistmanager.conf` file overriding the value? Other than that I'm not sure what could cause this behavior.

**Comment by indeedwatson** [comment]
I modified the .conf file following your instructions.If I want to update the script, would updating the .lua be enough, so that I can keep the .conf file as I configured it?

**Comment by jonniek** [comment]
Yes just replacing the lua is enough.

If the conf settings are not overriding the lua then make sure it's in the correct directory. The directory shoud be named `lua-settings` and be placed in the same directory as the script directory like this:  
```
lua-settings
scripts
watch_later
mpv.conf
input.conf
```

sidenote: you don't actually need to put `open_toggles=yes` as no to fix your issue

**Comment by indeedwatson** [comment]
Ah, it was the directories, I didn't realize I needed the lua-settings folder and had both files in /scripts

Seems to work fine now, thank you.
