### ISSUE TITLE
Maybe need an option to reset select condition?

### ISSUE THREAD

**Issue by kesdoputr** [donmaiq/Mpv-Playlistmanager#114]
Hello, when i have the setting **reset_cursor_on_close = true**

Then everytime i open the playlist the position will on the first file.

Now i process below action
●Open playlist, navigate to third file and select it (i use pink color for selected file)
![01](https://user-images.githubusercontent.com/16981364/210889177-a9cee04c-9a75-4ac1-9eb7-f67082b991a2.jpg)

●Close playlist (the third file still selected)
●Open playlist again, and we can see the position on the first file but selected
![02](https://user-images.githubusercontent.com/16981364/210889551-dbc1e7bf-93fe-481d-84f4-6d6a00e467dd.jpg)

Maybe it's better to have an option to reset the select condition when open playlist?
Thanks for your reading.

**Comment by jonniek** [comment]
I made `reset_cursor_on_close` reset the selection as well on close. I don't think it needs to be a separate setting.
