### ISSUE TITLE
Is there any way to mark videos in pl as watched without deleting them from pl

### ISSUE THREAD

**Issue by ghost** [donmaiq/Mpv-Playlistmanager#116]
Is there any way to mark videos in pl as watched without deleting them from pl, I saw your unseen playlist maker but I have to not delete urls from the playlist m3u, I have to keep them but when I open it in mpv it should be marked as watched, I also use yt-dlp to check playlist url if there is new video and it adds new url to the m3u so if we delete or make changes url in m3u script will be buggy

**Comment by jonniek** [comment]
It's not possible right now. Seems a bit of a niche usecase. What do you mean by "watched"?

There might be some way to create a generic styling functionality. Something like:
- playlistmanager has mapping of file -> style
- listen to script messages to add styles for a file
- have another script keep track of seen files and sending them to playlistmanager with some special styling

Not sure how well this would work.

**Comment by ghost** [comment]
I mean by watched when I open mpv with a playlist and literally watching from videos

**Comment by ghost** [comment]
@jonniek I found a way with using [another script](https://github.com/AN3223/dotfiles/blob/master/.config/mpv/scripts/auto-save-state.lua) that script save status and start where you left so that work really great with your playlist manager, thanks!
