### ISSUE TITLE
worst plugin i've ever used doesn't support mouse, can't dhow thumbnail 

### ISSUE THREAD

**Issue by aicynide** [donmaiq/Mpv-Playlistmanager#120]
How do you people find it useful. Its nothing compared to uosc

**Comment by FichteFoll** [comment]
1. It predates uosc.
2. uosc has a different goal with only partial overlap.
3. It still provides some functionality that uosc does not have (yet).
4. This is not an issue.

**Comment by aicynide** [comment]
What's its problem with mouse  support & thumbnail?

**Comment by 2084x** [comment]
this script is not an osc replacement so I don't understand why you would even compare it to uosc?

**Comment by poslat-pismo** [comment]
Can someone make playlistmanager's playlist work in the UOSC interface?
