### ISSUE TITLE
this issue still exists

### ISSUE THREAD

**Issue by sqq135** [donmaiq/Mpv-Playlistmanager#122]
https://github.com/jonniek/mpv-playlistmanager/issues/106
![屏幕截图 2023-06-27 211726](https://github.com/jonniek/mpv-playlistmanager/assets/78015121/0a85577c-d61b-418e-8a2b-bc81f7b03fb2)
I could not see the last one if the videos are more than 7 in the list.

**Comment by sqq135** [comment]
You can see  there are 12 videos, but I could't see the last one, even I move to the bottom.

**Comment by jonniek** [comment]
Yes, previous issue is still open. I'll try to find time to implement this soon. Closing this issue as duplicate and pinned the linked one.
