### ISSUE TITLE
Playlists displayed in osc

### ISSUE THREAD

**Issue by CNhjx** [donmaiq/Mpv-Playlistmanager#123]
Pressing the previous video or next video button in osd displays the playlist that comes with the mpv in osc.
![image](https://github.com/jonniek/mpv-playlistmanager/assets/57735696/63c5f15f-a63f-430e-ae73-93e4951aba0b)

 what can I do to make it display the playlist generated by playlistmanager?
![image](https://github.com/jonniek/mpv-playlistmanager/assets/57735696/a2ba1f90-490e-4664-bd70-628c7aec86ce)

**Comment by jonniek** [comment]
This is currently not possible with the default OSC and it feels like quite niche use case so I think it's unlikely it would be implemented. But you can still open an issue on mpv repository and see if someone knows a hack to customize the osc further than what official docs support.

If you find an OSC script that supports binding script messages to actions then you can use
```
script-message playlistmanager show playlist
```
