### ISSUE TITLE
Feature Request: Sort by date with correct placement in playlist when opening a file

### ISSUE THREAD

**Issue by tinglycraniumplacidly** [donmaiq/Mpv-Playlistmanager#125]
The `ls -1t | mpv playlist=- <file>` method referenced in #68 doesn't quite work for me because, while the file that gets loaded first is the correct one, it doesn't load that file in the right place in the playlist. Essentially it loads file, then hops to the first (last modified) file in playlist, then second (last modified). Ideally, it would load the file, then the next file in date order from the file, etc.

The behavior I'm looking for would be similar to feh's `-Smtime --start-at`. mpv's `--playlist-start=` only takes a number. It gets a bit more difficult since mpv can play directories...

**Comment by jonniek** [comment]
Does sorting the playlist with `default_sort=date-asc` not produce the result you want?

That one uses `mtime` for the sorting.

**Comment by KAWAGUCHI-Keiichi-source** [comment]
In my environment
I get sorted by name no matter which I specify

mpv --script-opts=default_sort=name-asc
or
mpv --script-opts=default_sort=date-asc

Is it just my environment?

**Comment by jonniek** [comment]
Can you provide details of your environment?

**Comment by KAWAGUCHI-Keiichi-source** [comment]
I've been struggling with this for months, please help me find a solution.

-- 
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

![Screenshot from 2024-08-03 19-03-30](https://github.com/user-attachments/assets/f19b7d5a-5afc-468a-9ce7-1c59f92e9125)

**Comment by poslat-pismo** [comment]
```
mpv --script-opts=playlistmanager-default_sort=date-asc
```

**Comment by KAWAGUCHI-Keiichi-source** [comment]
Thank you for your answer. I tried the method you suggested, but the result was the same.

![Screenshot from 2024-09-29 07-35-37](https://github.com/user-attachments/assets/9118a007-4018-4656-9c77-8a56b2a7a304)

**Comment by jonniek** [comment]
Hmm could it be that because the date is the same for the 000 - 004 files that they are ordered randomly? Maybe we should sort equal timestamps with some other fallback.

**Comment by jonniek** [comment]
Are you using `sortplaylist_on_file_add=yes`?

Does the files order correctly if you sort it by cycling with the `key_sortplaylist`?

**Comment by KAWAGUCHI-Keiichi-source** [comment]
set the following, but the situation remains the same.
Sorting is done. But sorted by name.

```
$ cat .config/mpv/script-opts/playlistmanager.conf |grep sortplaylist
key_sortplaylist=s
sortplaylist_on_file_add=yes
```

**Comment by jonniek** [comment]
Just to confirm, sorting is done by name after pressing `s` and using `default_sort=date-asc`?

Are you seeing any error log for `failed to read file info for` when running the sort?

Could you try this debug version that includes some info logging https://github.com/jonniek/mpv-playlistmanager/blob/sort-debug/playlistmanager.lua

It should print the file details out to console when the date-asc sorting is triggered, what we are interested in is the mtime field of the files.

**Comment by KAWAGUCHI-Keiichi-source** [comment]
![image](https://github.com/user-attachments/assets/e1575977-e24c-49f6-89ef-97bfedeb9b72)

[log.txt](https://github.com/user-attachments/files/17618960/log.txt)

I just tried it and it sorted by date.
This may be a misunderstanding on our part.
My apologies.
