### ISSUE TITLE
Where do I put this?

### ISSUE THREAD

**Issue by ghost** [donmaiq/Mpv-Playlistmanager#13]
I am new and I am sorry for putting this up as an issue, but I honestly don't know where to put this file. 
I tried putting it in the same directory as MPV which didn't work now I am stuck.

I'm on windows

**Comment by jgreco** [comment]
In the directory where your ``mpv.conf`` file is located (see: https://mpv.io/manual/stable/#files-on-windows) , create two new directories called ``scripts`` and ``script-opts``.   Place lua script files in the ``scripts`` directory and configuration files for those scripts in ``script-opts``

**Comment by ghost** [comment]
Okay so I need to get both of them

**Comment by ghost** [comment]
I saved both files and in the folder where I have the MPV conf. I created two new folders named them scripts and script-opts, then placed the files where they need to go. But still nothing, it doesn't work.

**Comment by ghost** [comment]
![fgad](https://user-images.githubusercontent.com/45624162/50062920-912db400-020e-11e9-882e-561f17b7e6b8.PNG)

**Comment by jgreco** [comment]
Per the documentation (since your config is in the same directory as your mpv.exe) I believe you should create a directory `portable_config` and place both `scripts` and `script-opts` directories inside it.

>If a directory named portable_config next to the mpv.exe exists, all config will be loaded from this directory only. Watch later config files are written to this directory as well. (This exists on Windows only and is redundant with $MPV_HOME. However, since Windows is very scripting unfriendly, a wrapper script just setting $MPV_HOME, like you could do it on other systems, won't work. portable_config is provided for convenience to get around this restriction.)

**Comment by ghost** [comment]
Created the portable folder placed script folders and still nothing.

**Comment by jgreco** [comment]
I'm afraid I'm out of ideas then.  I can only recommend reading over that manual page carefully and double checking everything.   I don't have a windows system available to me so that manual is all I have to go on.

**Comment by jgreco** [comment]
So that others can get a better idea of what's going on, it would be best if you could post a log using ``--log-file=not-working.log``

Also, are you pressing the right keys to activate the script?  It should activate when you press your shift and enter keys at the same time.

**Comment by ghost** [comment]
Aw, man... I guess it's okay then. This app seems really cool and would've been awesome if I could've used it on my system, but its fine. Thanks for all the support man, I'l close this for now.

**Comment by jonniek** [comment]
@smolseok the picture you posted seems like the wrong directory. It should probably be `C:\users\USERNAME\AppData\Roaming\mpv\` not the location of the mpv binary. If this one doesn't work either then maybe open up an issue on mpv repository with more details.
