### ISSUE TITLE
How to quit playlist after choosing a file from within it?

### ISSUE THREAD

**Issue by pafke2** [donmaiq/Mpv-Playlistmanager#136]
Hey, I've got the latest script version and it seems like the behaviour is changed.
The playlist used to disappear after you play an item from it, but now even after navigating and playing a file it still stays on top. How can I change it?

**Comment by pafke2** [comment]
After looking and setting to false close_playlist_on_playfile. It seems to work. But I have a question why change it in the first place? Its coold you added the functionality to display it or hide, but why change the default to true when it had always been false?

**Comment by jonniek** [comment]
Here is the context where it was changed https://github.com/jonniek/mpv-playlistmanager/pull/127 

I will re-consider the defaults
