### ISSUE TITLE
Question: Is there a command to load a previously saved playlists?

### ISSUE THREAD

**Issue by diegopds83** [donmaiq/Mpv-Playlistmanager#137]
I saw that there is a Save option and I was able to define a shortcut for it: `key_saveplaylist=s`. It worked.

But I didn't find a "`key_loadplaylist=`" option to bring back the playlists I saved.

The nearest was `key_loadfiles=` .  Is this? I configured the shortcut key `l` for this function and also added `"m3u"` in `loadfiles_filetypes =`

But this option seems to bring files in general (and is looking for my "home" directory `~` and not my playlists directory...).

Thanks in advance.

**Comment by jonniek** [comment]
No there currently is no good way to do this. There is an open pinned issue about it https://github.com/jonniek/mpv-playlistmanager/issues/70

As a workaround you could use as script like https://github.com/jonniek/mpv-filenavigator to navigate files in the disk.

I'll close this issue as duplicate. We can proceed discussion in the linked issue.
