### ISSUE TITLE
Playlist getting clipped on left side

### ISSUE THREAD

**Issue by raziel711** [donmaiq/Mpv-Playlistmanager#146]
I'm having an issue with the most recent version of the script which is causing the left edge of the playlist to be clipped.

I'm using the most recent version of Source Sans 3 for my font (https://github.com/adobe-fonts/source-sans/releases/) and this is what the OSD looks like:
![current](https://github.com/user-attachments/assets/7e4b72b8-2081-4471-8a45-4ab628e54d26)
The left side of the circles and arrows are not being displayed.

This is what the OSD looks like before https://github.com/jonniek/mpv-playlistmanager/commit/d4ebfc0b13ed074465263148d81dfee6d16c9a64:

![1911dc0](https://github.com/user-attachments/assets/73908627-6ee0-4f9e-b84e-ae6a081dd9bf)

I'm not sure why, but this might be dependent on the font.  I tried setting the OSD font to Arial, and I did not notice the same clipping that I did when using Source Sans 3.  Also, changing `text_padding_x` or `text_padding_y` did not have any impact.

These are my current settings:
[playlistmanager.txt](https://github.com/user-attachments/files/16421373/playlistmanager.txt)

**Comment by tupo2** [comment]
Same issue here.

**Comment by verygoodlee** [comment]
should be fixed in #148

**Comment by raziel711** [comment]
https://github.com/jonniek/mpv-playlistmanager/pull/148 works with my settings.  Thanks for the fix.
