### ISSUE TITLE
[FEATURE REQUEST] cli mode

### ISSUE THREAD

**Issue by realyukii** [donmaiq/Mpv-Playlistmanager#150]
It would be nice if this plugin support CLI mode (`--no-video`), the `SHIFT+ENTER` keybind trigger next track instead of show playlist in the current behaviour

**Comment by jonniek** [comment]
CLI mode should work somewhat now. Let me know if there is any issues.

Note that the default "SHIFT+ENTER" keybind doesn't seem to work in terminal. So I would recommend to use a different keybind that will work in both terminal and UI mode. If you want it to be conditional it could be possible with profiles https://mpv.io/manual/stable/#conditional-auto-profiles
