### ISSUE TITLE
Is it possible to set the backgroup color?

### ISSUE THREAD

**Issue by DreamMaoMao** [donmaiq/Mpv-Playlistmanager#153]
When some videos and subtitles have similar colors, the text will become difficult to read, can we set the background color?

**Comment by verygoodlee** [comment]
option `curtain_opacity` may help you, 0.6 is good for me, easy to read even in very bright scenes.
https://github.com/jonniek/mpv-playlistmanager/blob/c5526169ada174b0a45be55ee020a52126b54cc5/playlistmanager.conf#L129-L130
