### ISSUE TITLE
Playlist Scroll too Late

### ISSUE THREAD

**Issue by LenKiMo** [donmaiq/Mpv-Playlistmanager#16]
I am using a 1366*768 screen. When I call out the playlist, it would displays 5 or 6 files of the lists. But when I press down to scroll the list, the selected file icon would disappears in the bottom of screen. Only it arrives 11th file the list would start to scroll. Which means the 6th to 10th file of the list I can't see what it is, and I don't know which file is be selected now.

It seems like there is not relevant option to control this in `conf` file, is there any way to solve this problem?

**Comment by jonniek** [comment]
It sounds like some combination of `showamount` and `scale_playlist_by_window` setting should fix this. Can you post a picture/video of the problem, I think I didn't quite understand it correctly.

**Comment by LenKiMo** [comment]
Example 1:
![01.png](https://i.loli.net/2019/05/15/5cdbd415507d210388.png)
![02.png](https://i.loli.net/2019/05/15/5cdbd415488cb93690.png)

In a small video(640*360), playlist displays 9 items in the window (Pic 1), and if you move the selection to the 10th item, the list would not scroll, and the selection icon is out of the window (Pic 2).

Example 2:
![03.png](https://i.loli.net/2019/05/15/5cdbd415273f424704.png)

In a large video(1280*720), there are 6 items could see in the window.(Playlist 1/106)

![04.png](https://i.loli.net/2019/05/15/5cdbd415271a561059.png)

Move the selection to 6th item (Playlist 6/106), the list doesn't scroll, and the select icon out of the window.

![05.png](https://i.loli.net/2019/05/15/5cdbd4151efb874480.png)

When the selection arrives in 10th item, the list start to scroll, the first video hided as `...`. And the select icon still out of the window.

**Comment by jonniek** [comment]
You can set font size with `style_ass_tags={\fs10}` in .conf or `style_ass_tags ="{\\fs10}"` in lua file settings variable. Change the 10 to be a size that works for both video sizes. You can also change `showamount` to less than 16. Experimenting with `scale_playlist_by_window` could also help with different sized videos.

I will look into trying to fit the playlist to video size automatically.

**Comment by LenKiMo** [comment]
It helps. Thanks for your information.

By the way, may I ask where is the `script-opts` should in? In `mpv/script-opts` or `mpv/scripts/script-opts`?

**Comment by jonniek** [comment]
`mpv/script-opts/palylistmanager.conf`
