### ISSUE TITLE
Keep refreshing playlist view if toggled

### ISSUE THREAD

**Issue by wjtk4444** [donmaiq/Mpv-Playlistmanager#18]
I have a script called "music mode" that keeps displaying the playlist every second for one second when enabled. I think it'd be nice to have something like that for the playlist view.

Timer definition:
```{.lua}
-- music mode timer
-- when enabled, displays chapterlist / playlist every second for 1.05 seconds
-- 1.05 is used instead of one in order to prevent occasional blinking
local music_mode_timer = mp.add_periodic_timer(1, function ()
        if mp.get_property_number('chapters', 0) == 0 then
            mp.command('script-message osc-playlist 1.05')
        else
            mp.command('script-message osc-chapterlist 1.05')
        end
    end)

-- stop the timer (we don't want it running everytime when mpv starts)
music_mode_timer:stop()
```

Example usage, assuming a similar `playlist_timer`

```{.lua}
function toggle_playlist()
    if playlist_timer:is_enabled() then
       playlist_timer:stop()
    else
       playlust_timer:start()
    end
end

function show_playlist(duration)
     playlist_timer:start()
     mp.add_timeout(duration, function() 
             playlist_timer:stop()
        )
end
```

`add_timeout` is potentially unsafe in the following scenario
* show playlist for 10 seconds
* immediately toggle playlist off and on

as playlist will disappear after 10 seconds even though it shouldn't, but this can be easily solved with by capturing the timer object that will be returned by `add_timeout` and adding some check here and there.

By the way, is it possible to make the playlist view look more like playlist view from [osc.lua](https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua)? Like, auto-scaling how much elements fits on the screen and smaller font size.

**Comment by jonniek** [comment]
Is there any other use case for the re-render other than when playlist-count changes? Adding the following snippet will add support for that
```lua
function re_render_playlist(count)
  if playlist_visible then showplaylist() end
end
mp.observe_property('playlist-count', "number", re_render_playlist)
```

If you have some other cases where re-render is necessary to avoid playlist getting out of date let me know, else I will merge the above to master.

> By the way, is it possible to make the playlist view look more like playlist view from osc.lua? Like, auto-scaling how much elements fits on the screen and smaller font size.

There are various settings you can change to affect playlist visuals. The most versatile of them is `style_ass_tags` which lets you control font family, size, borders etc. `showamount` let's you control the max visible items.

**Comment by jonniek** [comment]
>auto-scaling how much elements fits on the screen

Or did you mean by this that the size is dynamic based on playlist length? I'm sorry I haven't used the native playlist so I'm not quite sure how it behaves.

**Comment by wjtk4444** [comment]
> Is there any other use case for the re-render other than when playlist-count changes? 

Two I can think of.
* title resolving using youtube-dl (assuming it'll be added in the future https://github.com/jonniek/mpv-playlistmanager/issues/15)
* It'll allow for an acutal *toggle* rather than playlist-view disappearing after 5, 100 or even 9999 seconds. I sometimes tend to leave mpv open for hours if not days.

> auto-scaling how much elements fits on the screen

Seems that I was wrong with this one, now that I check - it doesn't seem to scale at all. Anyway, I like how it doesn't take up the entire screen (fixed font size? not 100% sure as until today I was certain it scales with the number of playlist elements), also it looks consistent in comparison to chapterlist-view, which I use quite often.
Ideally, I'd like osc's playlist view, but with all the extra options your script provides. It's more of a personal preference than an actual issue, hence I didn't open a separate issue for it.

**Comment by jonniek** [comment]
>title resolving using youtube-dl (assuming it'll be added in the future #15)

This should already work https://github.com/jonniek/mpv-playlistmanager/blob/a52530ad5e5e584fb14c57f28eaf2c6ce5705158/playlistmanager.lua#L730-L733

>It'll allow for an actual toggle

It would be cool but timeout=4204967296 lasts 133 years. I'd imagine when someone needs to keep playlist open longer than that they can hack the functionality in. Implementing toggle doesn't need any timers, rather the toggle_playlist function just does:
```lua
function toggle_playlist()
  if playlist_visible then
    --removes keybinds, removes playlist drawing and sets playlist visible to false
    remove_keybinds() 
  else
    -- sets playlist visible to true, draws playlist and sets keybinds
    showplaylist()
  end
end
```
In this example all the keybindstimer references should be removed. It's quite a big diff but a lot cleaner than double timers. Obviously it doesn't really work together with a timer so I wont update master with this.

**Comment by jonniek** [comment]
>Ideally, I'd like osc's playlist view, but with all the extra options your script provides. It's more of a personal preference than an actual issue, hence I didn't open a separate issue for it.

I think it's a good idea that the default looks as similar as possible. I will take a look at this later this weekend.

**Comment by wjtk4444** [comment]
> It would be cool but timeout=4204967296 lasts 133 years

Isn't one hour the hard cap? I remember that I had a good reason for the timers, but it was loooong time ago and I don't remember the details. Maybe I'll do some tests later today.

from [the manual](https://mpv.io/manual/master/#options-osd-duration)
>--osd-duration=<time>
    Set the duration of the OSD messages in ms (default: 1000).

and from `mpv --list-options`
>--osd-duration                   Integer (0 to 3600000) (default: 1000)

**Comment by jonniek** [comment]
>Isn't one hour the hard cap

I didn't actually keep mpv open for an hour let alone 133 years so I don't know if it actually works. If 1 hour really is the cap then I agree it would be necessary to implement an actual toggle. In that case I think I will rethink the timer structure and try to implement toggle without timers and another toggle for with timers for the timeout.

>osd-duration Integer (0 to 3600000) (default: 1000)

It's not about osd-duration but the mp.add_periodic_timer(seconds) timeout since this script is no longer drawing the playlist on osd but with assdraw.

Maybe relevant part of source:
```c
int64_t mp_add_timeout(int64_t time_us, double timeout_sec)
{
    assert(time_us > 0); // mp_time_us() returns strictly positive values
    double t = MPCLAMP(timeout_sec * (1000 * 1000), -0x1p63, 0x1p63);
    int64_t ti = t == 0x1p63 ? INT64_MAX : (int64_t)t;
    if (ti > INT64_MAX - time_us)
        return INT64_MAX;
    if (ti <= -time_us)
        return 1;
    return time_us + ti;
}
```

**Comment by wjtk4444** [comment]
> this script is no longer drawing the playlist on osd but with assdraw.

Oh, nevermind me then. I assumed it's a really big osd-message because of the font size and style.

**Comment by jonniek** [comment]
That's the way it used to be, assdraw defaults to osd settings that's why it looks similar. For the time being you can edit the styles with the following setting:
```
--playlist ass style overrides inside curly brackets, \keyvalue is one field, extra \ for escape in lua
--example {\\fnUbuntu\\fs10\\b0\\bord1} equals: font=Ubuntu, size=10, bold=no, border=1
--read http://docs.aegisub.org/3.2/ASS_Tags/ for reference of tags
--undeclared tags will use default osd settings
--these styles will be used for the whole playlist. More specific styling will need to be hacked in
style_ass_tags = "",
```

**Comment by jonniek** [comment]
I refactored the rendering code to be a bit more simple and use less settings. I also made the default playlist look more like the native playlist. I hope you like the new look as much as I do!
