### ISSUE TITLE
Make saved playlist names more useful

### ISSUE THREAD

**Issue by jdsutherland** [donmaiq/Mpv-Playlistmanager#2]
Currently the playlist saves as a timestamp and length. It'd be nice if the filename gave some indication of the contents. For example, compare the following:

```diff
1497984651-size_13-playlist.m3u 
crash-course__computer-science__13.m3u
```

I'm currently trying this out (last two dirnames of the currently playing file):
```lua
local path = mp.get_property('path')
local cur_playing_basedirname = (path, "(.*/)(.*)/(.*)/(.*)", "%2__%3")
local savename = cur_playing_basedirname.."__"..length..".m3u"
local savepath = utils.join_path(settings.playlist_savepath, savename)
```
I removed the timestamp because I don't see any reason to want duplicates.

This works well for playlists contained in one directory (and using the`loadfiles` feature). It also allow combination with fzf for quickly fuzzy selecting a playlist.

This could be problematic if the playlist contains files from varying directories (I'm not sure that's even possible with the existing functionality of this script though).

Any interest?

**Comment by jonniek** [comment]
>This could be problematic if the playlist contains files from varying directories (I'm not sure that's even possible with the existing functionality of this script though).

It is possible if you meant saving playlists like that.

>I removed the timestamp because I don't see any reason to want duplicates.

The purpose of the timestamp was to have a new playlist always in a predictable location, in the end of the list of playlists. I guess a human readable timestamp would be more useful though.

That said I agree some indication of content would be useful. I will take a look later if I figure out some universally good solution for it.

**Comment by jonniek** [comment]
Changed timestamp to human readable in: aae4fbfee2da32cbf60353e7f63e8487c502f54a
