### ISSUE TITLE
A way to make the currently selected file have different colour

### ISSUE THREAD

**Issue by Naomi010Sentzke** [donmaiq/Mpv-Playlistmanager#20]
Would be awesome if like the Blackbox script, the selected file was in yellow(this makes it more identifiable).

**Comment by jonniek** [comment]
Thanks for the suggestion.

You can currently make this work with quite a verbose hack:
```
  normal_file = "{\\c&HAAAAAA&}○ %name",
  hovered_file = "{\\c&HAAAAAA&}● %name",
  selected_file = "{\\c&H0000FF&}➔ %name",
  playing_file = "{\\c&HAAAAAA&}▷ %name",
  playing_hovered_file = "{\\c&HAAAAAA&}▶ %name",
  playing_selected_file = "{\\c&H0000FF&}➤ %name",
```
Where AAAAAA or 0000FF are the respective reverse hex colors you want to use. I will try to think how this could be made more simple, especially defaulting to the osd color and ideally only having to define the selected_fille to have the color.

**Comment by Naomi010Sentzke** [comment]
Does not seem to work. I ran mpv through Command Prompt and got this
`[playlistmanager] script-opts/playlistmanager.conf:90 unknown key normal_file , ignoring
[playlistmanager] script-opts/playlistmanager.conf:91 unknown key hovered_file , ignoring
[playlistmanager] script-opts/playlistmanager.conf:92 unknown key selected_file , ignoring
[playlistmanager] script-opts/playlistmanager.conf:93 unknown key playing_file , ignoring
[playlistmanager] script-opts/playlistmanager.conf:94 unknown key playing_hovered_file , ignoring
[playlistmanager] script-opts/playlistmanager.conf:95 unknown key playing_selected_file , ignoring`

**Comment by jonniek** [comment]
If you use script-opts then you need to drop the extra \ which is used for escaping in lua.
```
normal_file={\c&HAAAAAA&}○ %name
hovered_file={\c&HAAAAAA&}● %name
selected_file={\c&H0000FF&}➔ %name
playing_file={\c&HAAAAAA&}▷ %name
playing_hovered_file={\c&HAAAAAA&}▶ %name
playing_selected_file={\c&H0000FF&}➤ %name
```

**Comment by Naomi010Sentzke** [comment]
Thanks I ended up using this
```
normal_file={\c&HFFFFFF&}○ %name
hovered_file={\c&H33FFFF&}● %name
selected_file={\c&HFF00FF&}➔ %name
playing_file={\c&HAAAAAA&}▷ %name
playing_hovered_file={\c&H00FF00&}▶ %name
playing_selected_file={\c&HFFFF00&}➤ %name
```
