### ISSUE TITLE
Using media titles only for URLs

### ISSUE THREAD

**Issue by Naomi010Sentzke** [donmaiq/Mpv-Playlistmanager#21]
I tried something like this in playlistmanager.conf, so that it will always display filenames, except for URLs(where it will display media titles).
```
[protocol.https]
prefer_titles=yes
```
Unfortunately, this is the result I get.
![Screenshot (792)](https://user-images.githubusercontent.com/53768184/65875903-dd18a680-e3a5-11e9-993c-404e85df6861.png)
Would be great if this was possible.

**Comment by jonniek** [comment]
The script config is not file specific. I think I can add another option like prefer_titles_for_urls.

The expected behavior in your screenshot should be that everything displays the filename and if you added a youtube url it would display the title, right?

**Comment by jonniek** [comment]
Can you try it with 93337d9b77b9eef9b272942983fb523fa238775b

I modified prefer_titles to be "all", "url" or "none".

**Comment by Naomi010Sentzke** [comment]
Thanks, it works as intended.
