### ISSUE TITLE
Doesn't work anymore after last file of playlist is over

### ISSUE THREAD

**Issue by joeonlist** [donmaiq/Mpv-Playlistmanager#22]
Hi jonniek,
I wrote about same issue about AppendURL.lua script few day ago.
I tried this one to manage interaction with a playlist created by adding various urls to the queue..
I looked for a way to show playlist and choose a previous or next video.
Your script contains that feature and works fine when a video of the playlist is being played.

But when the last playlist video ends and MPV window returns to idle mode, if I press SHIFT+ENTER to show my playlist, nothing happens anymore: seems the script is not recalled as expected.
(maybe same issue I opened few days ago for AppendURL script)

_PS.
I'm on Linux Slackware 14.2_
```
$ mpv --version
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Sep 24 14:06:28 CEST 2019
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: 4.1.4
```

**Comment by jonniek** [comment]
Hi, can you take a look if 0b9bfd133a2405a1f236d5182948020993ec746f fixes it?

**Comment by joeonlist** [comment]
Yes! It works now.
I noticed a (maybe) related issue:
- add some files to mpv playlist, by appendurl script for instance
- now go to the last audio/video file in the queue and let it end (also by pressing UP arrow for quickly skip regular playing speed)
- Ok, now we have our black MPV window in idle
- press shift+enter to show playlist and it appears (thanks to your above fix)
- now look at the first file of the queue: it has a right arrow instead of a circle like the other files in the queue. But no file is being played, mpv windows is in idle.
- now try to start playing that first file, so after SHIFT+ENTER, select the first file with arrows keys and then press ENTER to let it start.

I noticed it doesn't start at all.
I don't know if this issue can be related to the previous opened, but perhaps could be fixed within the same patch.

**Comment by jonniek** [comment]
Yeah it's a bit related. Seems like when idle the position counts as 0 which leads to this bug. Added a check for idle mode in 3b9aa948111fd0e4df8a706a320125b293b64f5d

**Comment by joeonlist** [comment]
OK!
Now it works!
So... for me it is fixed!

I'll wait few days to mark the issue closed for other tests by any other user...
Thanks again for your willingness!
Bye!  :)

**Comment by jonniek** [comment]
Yeah it might cause some side effects so if you notice anything weird let me know
