### ISSUE TITLE
Font size in playlist?

### ISSUE THREAD

**Issue by zohozer** [donmaiq/Mpv-Playlistmanager#23]
I installed this mpv plugin and it is working fine, unfortunately I can't find a way to change the default font size of the playlist which by default it is too big. It is there a way to set a custom font? I do read the documentation and tried to make changes in `playlistmanager.conf` file like adding this line of code `style_ass_tags={\fnUbuntu\fs10\b0\bord1} ` to the preferences but for now seems that the font size it is the same.

Please help.

**Comment by jonniek** [comment]
Is the other tags like font ubuntu or border working? If they are not the issue might be the location of your `playlistmanager.conf` file. Check the [docs](https://mpv.io/manual/master/#files-~/-config/mpv/script-opts/osc-conf) for correct location. After checking the location try altering the `fs10` to `fs5` and observe if there is any effect.

If that doesn't work you can also try to edit the configuration variable in the lua file. Change `style_ass_tags = "{}",` to `style_ass_tags = "{\\fs5}",` and observe if it has any effect. If nothing worked so far try changing the font, maybe some fonts are incompatible with the fs option?

If nothing worked so far can you let me know the location of your script and conf files and post your mpv version by running `mpv --version`. Can you also verify there is no visible errors in the console that is running mpv by running `mpv --idle`.

**Comment by zohozer** [comment]
Hi. Thank you for the reply. I was able to make the font smaller only by changing the `style_ass_tags` to `style_ass_tags = "{\\fs5}"` into the `playlistmanager.lua` file. I do made the same changes into the `playlistmanager.conf` file without any effect.

Maybe as an improvement will be great to have two or three shortcuts to make this changes from within the MPV interface. One to make the font size bigger, other to make the font size smaller, and third one to reset the size of the font size. Will be great if this modification can be made persistent between sessions.

**Comment by jonniek** [comment]
In that case your `playlistmanager.conf` is either in the wrong location or wrongly formatted.

> changes from within the MPV interface

This script already has quite too many keybindings and incrementing font size seems like a rather niche use case. I think most users will only use one static font size once they have found one that suits them.

**Comment by RomjanHossain** [comment]
sorry to bother you, but where should i put `playlistmanager.con`? 

i put it in `.config/mpv/lua-settings/playlistmanager.conf`. but it dosen't work.

**Comment by AchmadFathoni** [comment]
> sorry to bother you, but where should i put `playlistmanager.con`?
> 
> i put it in `.config/mpv/lua-settings/playlistmanager.conf`. but it dosen't work.

It is `~/.config/mpv/script-opts/playlistmanager.conf`
