### ISSUE TITLE
List with numbered files not sorted as expected

### ISSUE THREAD

**Issue by zohozer** [donmaiq/Mpv-Playlistmanager#24]
I have a lot of files into the same folder and all the files have a number at the beginning, like:

1.filename
2.filename
3.filename
.........
10.filename
20.filename

Unfortunately, when  creating a new playlist, the filenames are mixed and not in order. Instead to be 1, 2, 3, ... 10, 20, etc it is like 1, 10, 2, 20, 3... which obviously it is not the correct order of sorting the files.

It is possible to change the code and to sort the numbered files into the correct order?

Thank you.

**Comment by jonniek** [comment]
Are you talking about the sort function(CTRL+p)? The default value of `alphanumsort` option is true which handles sorting of this kind of directory. I tried with your example filenames and it's sorted in the expected order.
