### ISSUE TITLE
Not always caching titles in playlist

### ISSUE THREAD

**Issue by FichteFoll** [donmaiq/Mpv-Playlistmanager#25]
I noticed that playlist manager started caching the title of a url for a show since my last update (which was a long time ago), but it appears that the title is only cached if I request the playlist menu. 

Following is a screenshot of a playlist I played in mpv using the `--playlist` parameter and played through from the start. The two videos that show their actual title in the playlist menu are those during which I opened the playlist menu.

![2020-01-02_20-32-27](https://user-images.githubusercontent.com/931051/71688042-6d98c580-2d9f-11ea-9bf5-88172849bcbc.png)

Reproduction:

1. Load a playlist of urls into mpv (or append them dynamically)
2. skip a few videos (using your preferred binding for `playlist-next`; not using the menu)
3. open the playlist menu with shift+enter

You will only see a title for the latest item which you opened the menu with. The title will stick of you go to the next video/item.

Related: #15

**Comment by jonniek** [comment]
Currently the title is written to cache when rendering playlist. It is probably possible for playlistmanager to write the title to cache outside of rendering the playlist.

Is your expected behavior that the skipped items would also display titles?

**Comment by FichteFoll** [comment]
Yes, exactly. As soon as the video is loaded and its title is known, it should be cached so that you can more easily naviate already seen videos.

**Comment by jonniek** [comment]
Can you try the fix in: b64f640557c93c948c58959419383cb13b497807

**Comment by FichteFoll** [comment]
Works like a charm, thanks.

**Comment by remlap** [comment]
Hi I am still seeing this problem. It's my main reason for installing your script.

**Comment by jonniek** [comment]
Can you elaborate the steps to reproduce the issue and the expected result? Perhaps post a screenshot as well to clarify.

**Comment by remlap** [comment]
Loaded four urls into mpv:

`mpv https://www.youtube.com/watch\?v\=-KY1pDLulF4 https://www.youtube.com/watch\?v\=a3w9pmvpyDM https://www.youtube.com/watch\?v\=EyPLDItxGgA  https://www.youtube.com/watch\?v\=KxFliX-w6kI`

One title is missing:

![mpv-watch?v=-KY1pDLulF4-00:00:03 200-01](https://user-images.githubusercontent.com/5487111/80591572-d6bedb80-8a15-11ea-9bbc-98a4fae200cc.jpg)

**Comment by jonniek** [comment]
I could not reproduce.

Without `titleresolver.lua`:
1. After first video loads only it shows title
2. After navigating playlist only files that have been opened show title

With `titleresolver.lua`:
1. When first video loads all titles are displayed

If you are using `titleresolver.lua` and it fails to fetch the title then it's an unrelated issue to this. Currently the resolver script doesn't display or log any errors, I think I could update it to do so.

**Comment by remlap** [comment]
I am using titleresolver.lua, well its in my scripts folder.

**Comment by jonniek** [comment]
Can you replace it with this and look at the console if you get an error

```lua
local utils = require("mp.utils")
local msg = require("mp.msg")
-- resolve url title and send it back to playlistmanager
mp.register_script_message("resolveurltitle", function(filename)
  local args = { 'youtube-dl', '--no-playlist', '--flat-playlist', '-sJ', filename }
  local res = utils.subprocess({ args = args })
  if res.status == 0 then
    local json, err = utils.parse_json(res.stdout)
    if not err then
      local is_playlist = json['_type'] and json['_type'] == 'playlist'
      local title = (is_playlist and '[playlist]: ' or '') .. json['title']
      mp.commandv('script-message', 'playlistmanager', 'addurl', filename, title)
    else
      msg.error("Failed parsing json, reason: "..(err or "unknown"))
    end
  else
    msg.error("Failed to resolve url title "..filename.." Error: "..(res.error or "unknown"))
  end
end)
```

**Comment by remlap** [comment]
[titleresolver] Failed to resolve url title https://www.youtube.com/watch?v=a3w9pmvpyDM Error: killed

**Comment by jonniek** [comment]
Hmm, how about this:

```lua
local utils = require("mp.utils")
local msg = require("mp.msg")
-- resolve url title and send it back to playlistmanager
mp.register_script_message("resolveurltitle", function(filename)
  local args = { 'youtube-dl', '--no-playlist', '--flat-playlist', '-sJ', filename }
  local res = utils.subprocess({ args = args, cancellable = false })
  if res.status == 0 then
    local json, err = utils.parse_json(res.stdout)
    if not err then
      local is_playlist = json['_type'] and json['_type'] == 'playlist'
      local title = (is_playlist and '[playlist]: ' or '') .. json['title']
      mp.commandv('script-message', 'playlistmanager', 'addurl', filename, title)
    else
      msg.error("Failed parsing json, reason: "..(err or "unknown"))
    end
  else
    msg.error("Failed to resolve url title "..filename.." Error: "..(res.error or "unknown"))
  end
end)
```

**Comment by remlap** [comment]
That works perfectly.

**Comment by jonniek** [comment]
Alright, seems like perhaps subprocess runs before the file is loaded which is only allowed when cancellable is false. I will include this to the script.
