### ISSUE TITLE
Does not escape % characters in titles

### ISSUE THREAD

**Issue by FichteFoll** [donmaiq/Mpv-Playlistmanager#26]
Video titles containing `%s` in the title cause an exception when trying to open the playlist menu.

Example video: https://twitter.com/_jp53/status/1114233699652923392?s=21
Text: `Zelda can space short hop drifting dair in neutral as a fairly safe option, she can’t get as many conversions as fast fall dair but can still kill confirm with a rising dair at mid %s
#SSBU_Zelda`

Exception:
```
playlistmanager:
playlistmanager: stack traceback:
playlistmanager: 	[C]: in function 'gsub'
playlistmanager: 	/home/fichte/.config/mpv/scripts/playlistmanager.lua:342: in function </home/fichte/.config/mpv/scripts/playlistmanager.lua:340>
playlistmanager: 	(...tail calls...)
playlistmanager: 	/home/fichte/.config/mpv/scripts/playlistmanager.lua:401: in function 'draw_playlist'
playlistmanager: 	/home/fichte/.config/mpv/scripts/playlistmanager.lua:427: in function 'showplaylist'
playlistmanager: 	/home/fichte/.config/mpv/scripts/playlistmanager.lua:418: in function 'fn'
playlistmanager: 	mp.defaults:225: in function 'fn'
playlistmanager: 	mp.defaults:60: in function 'handler'
playlistmanager: 	mp.defaults:365: in function 'handler'
playlistmanager: 	mp.defaults:486: in function 'call_event_handlers'
playlistmanager: 	mp.defaults:520: in function 'dispatch_events'
playlistmanager: 	mp.defaults:479: in function <mp.defaults:478>
playlistmanager: 	[C]: in ?
playlistmanager: 	[C]: in ?
playlistmanager: Lua error: /home/fichte/.config/mpv/scripts/playlistmanager.lua:342: invalid use of '%' in replacement string
```

**Comment by jonniek** [comment]
Hi,

Can you post your lua version? Run a mpv script with `print(_G._VERSION)` in any script file. My system uses lua 5.1 and it does not crash on this issue. However, it does not display the % at all.

I can reproduce this issue on Lua version 5.3 in [lua demo](https://www.lua.org/cgi-bin/demo)
```lua
local name = "test name % with percent"
local format = "-> %filename"

-- This escape fixes the crash
-- name = name:gsub("%%", "%%%%")

print(format:gsub("%%filename", name))
```

Could you try editing your `stripfilename` function to `return tmp:gsub("%%", "%%%%")` instead of `return tmp` and let me know if it fixes your issue.

**Comment by FichteFoll** [comment]
My system lua is 5.3 (I'm on Arch) and mpv uses 5.2 according to `_G._VERSION`.

Making the suggested change fixes the crash but ends up displaying two `%` characters.

![2020-01-04_13-54-43](https://user-images.githubusercontent.com/931051/71765867-caa88e80-2ef9-11ea-9cd8-8e0f30565b6e.png)

**Comment by FichteFoll** [comment]
With https://github.com/jonniek/mpv-playlistmanager/commit/b64f640557c93c948c58959419383cb13b497807 applied as well, the above change renders `%name` for all entries.

**Comment by jonniek** [comment]
Oh right, still need to undo the escaping. Can you test with: d9a268f611508aee21eaa2b4ec48e8d4badb5b11 

Works for me both in 5.1 and 5.2 version.

**Comment by FichteFoll** [comment]
Confirmed working. Thanks for the quick replies and fix.
