### ISSUE TITLE
About color setting

### ISSUE THREAD

**Issue by kesdoputr** [donmaiq/Mpv-Playlistmanager#29]
I see this issue
https://github.com/jonniek/mpv-playlistmanager/issues/20

But i don't know how to setting the **respective reverse hex colors**

If i want to use E6E6FA and FFF8DC, how can i chagne it to right format?

And if it support alpha channel?
ex.Now my OSD color in mpv.conf is osd-color="#CCE6E6FA" with CC for the transparent.

Thank you for your watching.

**Comment by jonniek** [comment]
Hi,

Reverse hex means instead of RGB order it's BGR.

Some documentation for ass tag color can be found in http://docs.aegisub.org/3.2/ASS_Tags/#\c

To match your current osd-color I think the following should work `\alpha&HCC&\c&HFAE6E6&`

**Comment by kesdoputr** [comment]
Thanks for your quick reply, 
I will check the document later.
