### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by ghost** [donmaiq/Mpv-Playlistmanager#3]
Can you make sorting case-insensitive? And it would be great, if you add option to sort on load of files, not only on mpv start.

**Comment by jonniek** [comment]
Fixed case sensitivity in 9eca244ae31db06590a75f9021ac79c6aaa22107

I think adding a sort on load of files is not a smart idea since the playlist starts from beginning after every sort. With this feature I would imagine it would be better if it sorted it quietly. The problem with implementing this is that I did not find any event from mpv documentation for when a file is added to the playlist during playback making it impossible to make the sort execute every time a file is added.

**Comment by ghost** [comment]
Alright, thanks.

**Comment by jonniek** [comment]
I made a new autosort on file added feature in 8ede686068498789a0fe6f889a5cd7201fede8b9

Sorting works now in the background, and when the playlist size increases you have a setting that will automatically sort it. I didn't realize earlier property listeners were so versatile!

If you could test it out and report how it works I would appreciate it!

**Comment by ghost** [comment]
Tested it a little:
- with option `sortplaylist_on_file_add=yes` playlist doesn't sorted automatically, when files are added
- when i start sorting manually, it works well in the background 
- with options `loadfiles_on_start=yes` and `sortplaylist_on_start=yes` playlist is loaded and sorted, but it starts a video from the beginning of a playlist

Also, i've noticed that symbols like `『` sorted at the end, while symbols like `#` sorted at the beginning of a playlist. Maybe they both should be sorted at the beginning ?

**Comment by jonniek** [comment]
> playlist doesn't sorted automatically, when files are added

How did you add the files? I noticed that if you use the managers loadfiles feature it will not sort afterward which i fixed. Drag and drop, and other scripts manipulating the playlist size triggers the sort for me.

>  with options `loadfiles_on_start=yes` and `sortplaylist_on_start=yes` playlist is loaded and sorted, but it starts a video from the beginning of a playlist

Good catch, fixed it.

> symbols like 『 sorted at the end, while symbols like # sorted at the beginning of a playlist

The only simple solution I can think of is to remove all special characters before sorting but that will cause more harm than good I think.

If you try the new fixes now there is also a new configs so if you use a config file be sure to update it.

**Comment by ghost** [comment]
> I noticed that if you use the managers loadfiles feature it will not sort afterward which i fixed. 

Yes, i added files with loadfiles function, and now it works. Also if a video have different filename and title when i load new videos it is sorted by the title instead of the filename.

> Drag and drop

When i open a video and then drop in bunch of new videos, playlist is sorted (with `sortplaylist_on_file_add=yes`) and it starts a video from the beginning of a playlist, the way mpv does it without the script. But if i open new window with empty playlist and then drop new videos playlist isn't sorted.

> will cause more harm than good I think

Yeah, it's a bad solution.

**Comment by jonniek** [comment]
> it is sorted by the title instead of the filename

Fixed this. Sort will always use filename now(custom stripping applied still though).

> But if i open new window with empty playlist and then drop new videos playlist isn't sorted.

Sort on file add is only activated after the first file has loaded, to separate the functionality from sort on start. And sort on start needs to wait for file load because playlists will open initially as one file.

**Comment by ghost** [comment]
Now all the issues with sort seem to be fixed. Thank you.

And one minor issue, but not about sorting. I think, with option `prefer_titles=no` playing header should also show a filename instead of a title.

**Comment by jonniek** [comment]
Fixed this dilemma. Now you can configure the playlist header for yourself.  
Default:
```
playlist_header = "Playing: %mediatitle%N%NPlaylist - %cursor/%plen",
```
Change %mediatitle to %filename
