### ISSUE TITLE
Reverse Playlist Order

### ISSUE THREAD

**Issue by mortyobnoxious** [donmaiq/Mpv-Playlistmanager#30]
Hi, is it possible to add a function to "reverse playlist order"?

This would be pretty useful for Youtube playlists such as this:
`https://www.youtube.com/playlist?list=PLw-6MW2y1UEq2puHjam-QZAHe5iuQaseL`

**Comment by jonniek** [comment]
Sounds like an useful feature. I will implement this soon.

**Comment by mortyobnoxious** [comment]
Thank you.

**Comment by jonniek** [comment]
Done 2ee19f5325d1a6db66f5e6159275f6ee5870bb29 9f9e067c20e2848108db14a64c8ff2b7a45cbb15

Let me know if you have any issues with it.

**Comment by mortyobnoxious** [comment]
It works great. Thank you.
