### ISSUE TITLE
Playlist actions in an interactive menu

### ISSUE THREAD

**Issue by jonniek** [donmaiq/Mpv-Playlistmanager#35]
I think having a menu like the following could be useful
```
Playlistmanager actions

○ sort playlist alphanumerically
● sort playlist alphabetically
○ reverse playlist
○ save playlist
○ load playlist
○ shuffle playlist
```

_Originally posted by @jonniek in https://github.com/jonniek/mpv-scripts/issues/5#issuecomment-616820024_

This could be a separate script(playlistmenu.lua?) that uses script messages for the actions.

**Comment by mortyobnoxious** [comment]
This is somewhat out of place but I tried and couldn't manage to do it, i have to ask, you can completely ignore btw, sorry in advance.

Is there a way to use "your menu" to execute functions instead of keybindings.
For example I have multiple functions like this:
```
function functionName1 ()
.....
end
```

```
function functionName2 ()
.....
end
```
etc.

Instead of using keybinding like this:
`mp.add_key_binding("Ctrl+a", "functionName1", functionName1)`

How can i use "your menu" to execute functions not just for playlistmanager's but for other functions that i have.

I've looked all the scripts with "interactive menu" and couldn't figure it out to strip it to use since i don't know coding well. Sorry again since this is more like personal issue rather than playlistmanager.

**Comment by jonniek** [comment]
Scripts can communicate with eachother via script messages.

So if you have your own functions in a lua file
```lua
function functionName1 (param)
.....
end

mp.register_script_message("functionName1", functionName1)
```

Now another script could call this simply by

```lua
mp.commandv('script-message', 'functionName1', 'some_value')
```

**Comment by CogentRedTester** [comment]
The relevant sections seem to be lines 417-554.

You'd need to maintain and update an ass(subtitle) layer containing the menu items as text (this is what you see), then dynamically bind keybinds like the arrows and enter when the list is open to change variables which correspond to the selected entry in the list. You'd then need to unbind these when the list is hidden.

If you store the different functions you want in a table then you can call the corresponding function for the currently selected item in the menu.

**Comment by CogentRedTester** [comment]
On a separate note Jonniek, what if this functionality were adapted into a separate script that could work with any entered script-message? If a standard way of parsing additional options were added to the config file it could work. It could theoretically be adapted for any command.

**Comment by mortyobnoxious** [comment]
@jonniek , @CogentRedTester Thank you, I will try again.

**Comment by jonniek** [comment]
@CogentRedTester  A generic editable menu seems to make more sense.

A quick and dirty demo copy pasted from playlistmanager. I will work on refining this a bit.

```lua


local settings = {
  display_timeout = 5,

  loop_cursor = true,

  key_moveup = "UP WHEEL_UP",
  key_movedown = "DOWN WHEEL_DOWN",
  key_execute = "ENTER MBTN_MID",
  key_closemenu = "ESC MBTN_RIGHT",

  style_ass_tags = "",
  text_padding_x = 10,
  text_padding_y = 30,
  scale_by_window = false,
}

local menu_items = {
  {
    label = "hello world",
    action = function ()
      mp.commandv("show-text", "Hello world")
    end
  },
  {
    label = "quit",
    action = function ()
      mp.commandv("quit")
    end
  }
}

local utils = require("mp.utils")
local msg = require("mp.msg")
local assdraw = require("mp.assdraw")

local menu_size = 0
for _ in pairs(menu_items) do menu_size = menu_size + 1 end

local menu_visible = false
local cursor = 1

function execute()
  menu_items[cursor].action()
  remove_keybinds()
end

function toggle_menu()
  if menu_visible then
    remove_keybinds()
    return
  end
  render()
end

function render() 
  add_keybinds()

  local ass = assdraw.ass_new()
  ass:new_event()
  ass:pos(settings.text_padding_x, settings.text_padding_y)
  ass:append(settings.style_ass_tags)

  for index, item in ipairs(menu_items) do
    local selected = index == cursor
    local prefix = selected and "● " or "○ "
    ass:append(prefix .. item.label .. "\\N")
  end

  local w, h = mp.get_osd_size()
  if settings.scale_by_window then w,h = 0, 0 end
  mp.set_osd_ass(w, h, ass.text)

  menu_visible = true
  keybindstimer:kill()
  keybindstimer:resume()
end

function moveup()
  if cursor ~= 1 then
    cursor = cursor - 1
  elseif settings.loop_cursor then
    cursor = menu_size
  end
  render()
end

function movedown()
  if cursor ~= menu_size then
    cursor = cursor + 1
  elseif settings.loop_cursor then
    cursor = 1
  end
  render()
end

function bind_keys(keys, name, func, opts)
  if not keys then
    mp.add_forced_key_binding(keys, name, func, opts)
    return
  end
  local i = 1
  for key in keys:gmatch("[^%s]+") do
    local prefix = i == 1 and '' or i
    mp.add_forced_key_binding(key, name..prefix, func, opts)
    i = i + 1
  end
end

function unbind_keys(keys, name)
  if not keys then
    mp.remove_key_binding(name)
    return
  end
  local i = 1
  for key in keys:gmatch("[^%s]+") do
    local prefix = i == 1 and '' or i
    mp.remove_key_binding(name..prefix)
    i = i + 1
  end
end

function add_keybinds()
  bind_keys(settings.key_moveup, 'simplemenu-moveup', moveup, "repeatable")
  bind_keys(settings.key_movedown, 'simplemenu-movedown', movedown, "repeatable")
  bind_keys(settings.key_execute, 'simplemenu-execute', execute)
  bind_keys(settings.key_closemenu, 'simplemenu-closemenu', remove_keybinds)
end

function remove_keybinds()
  keybindstimer:kill()
  keybindstimer = mp.add_periodic_timer(settings.display_timeout, remove_keybinds)
  keybindstimer:kill()
  menu_visible = false
  mp.set_osd_ass(0, 0, "")
  if settings.dynamic_binds then
    unbind_keys(settings.key_moveup, 'simplemenu-moveup')
    unbind_keys(settings.key_movedown, 'simplemenu-movedown')
    unbind_keys(settings.key_execute, 'simplemenu-execute')
    unbind_keys(settings.key_closemenu, 'simplemenu-closemenu')
  end
end

keybindstimer = mp.add_periodic_timer(settings.display_timeout, remove_keybinds)
keybindstimer:kill()

mp.register_script_message("simplemenu-toggle", toggle_menu)
mp.add_key_binding("MBTN_MID", "simplemenu-toggle", toggle_menu)
```

**Comment by CogentRedTester** [comment]
Though if you had an external json settings file, then you could get the menu by running utils.parse_json() on that file. 'action' could then be a command formatted as a json array, which is easy to convert into a command.

See my [profile-commands](https://github.com/CogentRedTester/mpv-scripts/blob/master/profile-command.lua) script for how easy it is to do.

**Comment by mortyobnoxious** [comment]
@jonniek I used that demo it works pretty nice. But "remove_keybinds" doesn't seem to work.

Btw, using these two  `and "◉ " or "○ "` instead of `and "● " or "○ "` prevent text from moving if you consider.



![jcswhWXM2Y](https://user-images.githubusercontent.com/42044258/81279875-59701800-9060-11ea-9912-184780db701d.gif)
![jGwJSs9eBj](https://user-images.githubusercontent.com/42044258/81279882-5b39db80-9060-11ea-9bcf-3e1998753405.gif)

**Comment by CogentRedTester** [comment]
It doesn't work because it still has the settings.dynamic_binds check inside the remove_keybinds() function

**Comment by jonniek** [comment]
> Btw, using these two `and "◉ " or "○ "` instead of `and "● " or "○ "` prevent text from moving if you consider.

Hmm, for me it's the opposite. Perhaps this is font related?

> Though if you had an external json settings file, then you could get the menu by running utils.parse_json() on that file. 'action' could then be a command formatted as a json array, which is easy to convert into a command.

I'm not sure I understand the benefit of it being json. I guess if there is no usecases for the action to be a function then it would be more simple to have it as an array though. Or I guess it's easy enough to support both by checking the type.

```lua
{
  label = "quit"
  command = "quit"
},
{
  label = "Hello world",
  command = {"show-text", "Hello world"}
},
{
  label = "Complex",
  command = function()
    --do something non mpv related without using script-messages
  end
}
```

**Comment by mortyobnoxious** [comment]
Oh, it's font related. I removed "osd-font='Trebuchet MS'" from mpv.conf and it's now opposite.

**Comment by CogentRedTester** [comment]
The advantage of using json is that you can just call utils.parse_json() and call it a day. Of course this is very much from the perspective of the script being user customisable. If you wanted to make this menu self contained within the script then there would be no reason to.

**Comment by CogentRedTester** [comment]
For example [this modified version of the script](https://gist.github.com/CogentRedTester/d807a71bdc0131c28f7f434e0f5e8a90). Can now allow the user to add any and all commands they want to the menu.

Try putting the following code into a file called 'list.json' inside ~~/script-opts:

```
[
    {
      "label": "hello world",
      "action": ["show-text", "Hello world"]
    },
    {
        "label": "greetings!",
        "action": ["show-text", "Greetings!"]
    },
    {
      "label": "quit",
      "action": ["quit"]
    }
]
```

**Comment by CogentRedTester** [comment]
I just modified it to have the json work with multiple commands per option. 

The advantage of this is that the whole menu is safely inside a separate config file. That means the user doesn't need to do any fiddling with the code; we can immediately tell if the syntax is wrong because the json will return nil, and it just makes it really easy to add more options.

![image](https://user-images.githubusercontent.com/57207260/81289741-0faa2080-90a6-11ea-934f-5a06b4213e5b.png)

**Comment by jonniek** [comment]
I see, that's quite nice. I guess the inline functions are better off as separate scripts anyway.

**Comment by CogentRedTester** [comment]
Yea, if the purpose of such a script is just to be a generic menu there is no need for inline function.

Are we going to keep this as theory or put it into a repository somewhere?

**Comment by jonniek** [comment]
https://github.com/jonniek/mpv-menu

I'll keep this issue open until there is a `menu.json` in this repo with playlistmanager features added.
