### ISSUE TITLE
Relative path for saving a playlist

### ISSUE THREAD

**Issue by slideray** [donmaiq/Mpv-Playlistmanager#36]
Is it possible to specify a relative path for saving a playlist? it is very inconvenient to set the full path every time, you can forget to do it on the new system and the functionality is lost

**Comment by jonniek** [comment]
Relative to what?

- launch directory?
- mpv config directory?
- home directory?

Would `mpv/playlists` be ok for your usecase?

There is a PR working on this #34

**Comment by slideray** [comment]
any way, any option will do, as long as the path is not tied to a single address.

Ideally, of course, this would be a subdirectory of the configuration
/home/user/.config/mpv/playlists
only not linked to a specific user

**Comment by jonniek** [comment]
Added 9861704585049ed4aafd07efcc69c1325668aad1
