### ISSUE TITLE
Too slow when sorting large list

### ISSUE THREAD

**Issue by aca** [donmaiq/Mpv-Playlistmanager#37]
It works but it's too slow when opening more than thousands of files.
It leaves zombie process when I close mpv while sorting.
I'm not familiar with mpv api, is it possible to replace sorting algorithm?
Thanks for the great plugin by the way.

**Comment by jonniek** [comment]
Sorting is using insertion sort so it's a bit slow.

I can take a look at changing the algorithm.

**Comment by zsugabubus** [comment]
> I can take a look at changing the algorithm.

If you are still looking for an algorithm, in [one of my scripts](https://github.com/zsugabubus/dotfiles/blob/master/.config/mpv/scripts/playlist-filtersort.lua) I use Lua's `table.sort()` and then 2*N `playlist-move`s (swaps) to sort the playlist.

It is able to filter+sort 10k items around 3 seconds on my washing machine, so maybe it could help to speed up things here.

**Comment by jonniek** [comment]
Thanks @zsugabubus that is crazy fast!

I implemented the algo and tried with 30k files and it sorted them in 5 sec. I think it's probably fine to use the double move always.
