### ISSUE TITLE
Option to show media-title

### ISSUE THREAD

**Issue by kesdoputr** [donmaiq/Mpv-Playlistmanager#4]
When i use mpv to open a youtube playlist

The media title on osc show the correct media title of the video
and the default playlist (right click on the arrow)show playlist with media title
https://i.imgur.com/CWmbSi8.jpg
But when i press shift+enter to call playlist from playlistmanager
the playlist seems to show filename so i can only see the url that i can't
switch to the title i want to see.
https://i.imgur.com/F4Igy79.jpg

(ps.the title on example picture is chinese)

Maybe a option to choice show filename or media-title is better?
Thanks for your reply ^_^

**Comment by jonniek** [comment]
Thanks for the issue. 

There is no way to check the media-title until the file has loaded. In this case the playlist would need to make a http request for every item in advance. I will look into how feasible this feature is and report back later.

**Comment by kesdoputr** [comment]
Thanks for the reply.I found that when i use 
**script-message playlistmanager show filename**,it can show correct media-title of the video not url
ps.when i use right click on osc title(will show filename by osc default)it will show the url

but use
**script-message playlistmanager show playlist** just show the url of the video

by the way the playlist i test is below
https://www.youtube.com/playlist?list=PL87jg1FsSTNgpx5emEyk2F45EwXumaDtq

**Comment by jonniek** [comment]
Sorry i misunderstood your first post at first. I was surprised to learn there was a title property for playlist entries.

Fixed youtube playlists not having titles in 2ac4f883edfbaf0f98ea0494197ef5750902f2db
So if you open a playlist like this `mpv https://www.youtube.com/watch?list=PLFgquLnL59alCl_2TQvOiD5Vgm1hCaGSI` then all the files should have a title instead of a url.

I will not implement a separate parser for added urls or urls that were not loaded as a youtubedl playlist for now.

**Comment by kesdoputr** [comment]
Hello thanks for the update,it's work fine on youtube playlist but i have some small problems and suggestions.
01.If **just one youtube url** is paste,it can't show title but show url like before
ex.
playlist by mpv default
http://i.imgur.com/zbEcWUi.jpg
playlist by playlist playlistmanager
http://i.imgur.com/vQ0or4d.jpg

it's work fine.
But with one url like https://www.youtube.com/watch?v=_1lOwCaUKdw
will show url like before
http://i.imgur.com/sejTob8.jpg

02.Can i setup the **playlist font size**?When playslist number is small (like the picture above it has 8 files)
the playlist font size is similiar but when the playlist number is big
ex.(has 168 files)
playlist by mpv default
http://i.imgur.com/KDEfO13.jpg
playlist by playlist playlistmanager
http://i.imgur.com/X0fcnwC.jpg

i think it's better if i can make the font size smaller.

03.When i use **drag&drop local files** to mpv(i use windows build),it will **show path not only filename**.
The previous version of playlistmanager don't have this problem,and when i use command line
mpv file.mp4 it just show filename.
ex.
use command line to open 3 files
http://i.imgur.com/cMzz0nF.jpg
use drag&drop to open 3 files
http://i.imgur.com/MBNNark.jpg

04.When i use mpv --playlist sample.list and list is like
h:\download\01.mp4
h:\download\02.mp4
....

like the problem above it will show file path,and previous previous version of playlistmanager don't have this problem.
http://i.imgur.com/9KRJcU7.jpg
with previous version
http://i.imgur.com/0JTZwcC.jpg

Thank you for watching^_^

**Comment by kesdoputr** [comment]
Sorry i have one more problem not with youtube.
I use mpv to play other site video like
http://www.bilibili.com/video/av12845790/

We can see the **now playing show correct media-title** same with the title on OSC
http://i.imgur.com/ozRBKaE.jpg
but playlist just show url

Because show_playing_header can get correct media-title, if it is possible to let 
playlist to get the title like the playing_header does?

PS.with previous playlistmanager it's the same that show_playing_header can 
get correct meida-title.

Thx for reply.

**Comment by jonniek** [comment]
> If just one youtube url is paste,it can't show title but show url like before

Oh I see what you mean. Playing file will now have media title if it differs from the filename. 2dfdfcbcf80031ab53f3bfb8aa8472d6744b20f4

> Can i setup the playlist font size?

I am working on this. I feel like manipulating the osd font size temporarily is not a good solution so I might just port it to draw itself instead of using osd.

> show path not only filename.

Yeah I changed so that split path will not affect url files but forgot the check for windows paths. Fixed in dc0269bea0cd348eb831fafa3b0361715806cf74 

Can you confirm if these changes fixed your problems?

**Comment by kesdoputr** [comment]
Hello,i have tried new version and my problems seems all ok.
It's work fine now,thanks for the modify.^_^

**Comment by jonniek** [comment]
By the way I added font-size and other settings in 1ad78f4423d57e331b78f423d8c02f639077b28f

**Comment by kesdoputr** [comment]
Thank you, i will try later for the version.
