### ISSUE TITLE
Using Mouse Wheel

### ISSUE THREAD

**Issue by mortyobnoxious** [donmaiq/Mpv-Playlistmanager#43]
Is it possible to use mouse wheel to:

> WHEEL_UP/WHEEL_DOWN to move selection
> MBTN_MID to load highlighted entry
> MBTN_RIGHT to exit

Just like this script: https://github.com/hacel/mpv-scripts/blob/master/recent.lua

**Comment by mortyobnoxious** [comment]
I did this and it kind of worked, i guess.
```
-- to bind multiple keys separate them by a space
key_moveup = "UP WHEEL_UP",
key_movedown = "DOWN WHEEL_DOWN",
key_selectfile = "RIGHT LEFT",
key_unselectfile = "",
key_playfile = "ENTER MBTN_MID",
key_removefile = "BS DEL",
key_closeplaylist = "ESC MBTN_RIGHT",
```

**Comment by jonniek** [comment]
I like the scroll idea, but I think to use mouse controls you need to have opening, selectfile and removefile also on mouse binds.

I could add some example in readme how to add mouse support.

**Comment by mortyobnoxious** [comment]
I tried using multiple mouse bindings at the same time for those but couldn't manage to make it work properly.
For example:
`MBTN_LEFT-MBTN_RIGHT` to `key_removefile` but not working all the time.

**Comment by jonniek** [comment]
I think it's quite common to use volume/seek for scrolling and I don't want to override those by default.
