### ISSUE TITLE
How to overwrite key bindings set by playlistmanager.lua

### ISSUE THREAD

**Issue by c02y** [donmaiq/Mpv-Playlistmanager#44]
https://github.com/mpv-player/mpv/issues/7685

**Comment by jonniek** [comment]
`p show-progress` in input.conf works for me.

Perhaps I should remove some default keybindings and let the user bind them if they use the features. One thing I dislike is the that this script overrides default mpv bindings that cannot be recovered without knowing the name of the command or by editing the script.

**Comment by c02y** [comment]
Problem solved, the line **default-bindings start** in input.conf shouldn't be enabled.
