### ISSUE TITLE
Updating m3u File

### ISSUE THREAD

**Issue by mortyobnoxious** [donmaiq/Mpv-Playlistmanager#45]
Is it possible to update local m3u file when an item/video is removed(`removefile`) from playlist?

For example when I delete `Title 1` from playlist by pressing BS.
```
#EXTINF:,Title 1
https://youtu.be/abcdefghf
#EXTINF:,Title 2
https://youtu.be/fhgadwasz
```
It will update local m3u file like this:
```
#EXTINF:,Title 2
https://youtu.be/fhgadwasz
```

**Comment by jonniek** [comment]
Would you expect this feature to work from playlist to playlist independently?

Anyway this seems like quite a tricky feature. Simplest solution would be to allow saving playlist with a custom name, then just rewriting with the same name.

I've been thinking about a playlist overhaul that would introduce a list of saved playlists. If we opened the playlist from the saved list, there could be this kind of feature in theory.

**Comment by mortyobnoxious** [comment]
I thought it would be possible to get playlist path and playlist name and overwrite it with updated playlist whenever an item/video is deleted but if it's not that simple, I'm up for "playlist overhaul" idea. You can close this if you prefer, since it will be tricky.

**Comment by CogentRedTester** [comment]
What's your use case for this? You want to keep a playlist that's always in sync with the current mpv playlist? What for?

**Comment by mortyobnoxious** [comment]
I save YouTube playlists as m3u to desktop and play it time to time from the desktop. But mpv, most of the time, doesn't remember last played video (even though I use autosave.lua) from the playlist and play previous video from the playlist. So I delete the videos I've watched from the playlist to continue where I left.

Another use case is music and podcast playlists.
- I remove some songs from playlist.
- I remove some podcast episodes from playlist.
etc.

**Comment by FichteFoll** [comment]
Do you know about mpv's save quit feature when pressing `Q` (that's an upper-case q)?

**Comment by mortyobnoxious** [comment]
Yes. As i say, i even have autosave.lua. That doesn't make playlists start where i left.

**Comment by jonniek** [comment]
It's possible to overwrite playlist now by giving the same name https://github.com/jonniek/mpv-playlistmanager/issues/50

Not sure if it could somehow put the default name as the playlist that was initially opened, that would improve your usecase a lot. Looking at the docs it looks like this is not possible. So only option would be to have select the playlist internally from playlistmanager so it could keep track of the name.

**Comment by mortyobnoxious** [comment]
Yes, there seems to be no way to get `playlist-url` or `playlist-name`.

Thank you, though. Giving it the exact same name works great.
