### ISSUE TITLE
Special Unicode support for Windows probably no longer needed

### ISSUE THREAD

**Issue by Silver-Fullbuster** [donmaiq/Mpv-Playlistmanager#47]
There has been a recent commit in mpv https://github.com/mpv-player/mpv/commit/bb231889fdd2ee0f519bdb1c756b61ceefd5584b which as per the description may no longer require special workarounds for supporting Unicode characters in filenames or directories in Windows. If I get this correctly, the script can probably remove any of the special windows stuff it's doing

Assuming what I understood is correct, the issue is that it works on Windows 10 v1903 or above only.

**Comment by jonniek** [comment]
Thanks for letting me know. This script migrated to use powershell for most functions some time ago.

It seems like the only Lua IO this script is using is https://github.com/jonniek/mpv-playlistmanager/blob/8f01f38d71bdf02a3b61988a940a5fc0db3b573c/playlistmanager.lua#L710

Not sure if it suffered from this issue but glad to know it might be more reliable now.
