### ISSUE TITLE
Showing Chapter List

### ISSUE THREAD

**Issue by mortyobnoxious** [donmaiq/Mpv-Playlistmanager#48]
Is it possible to have an option to show chapter lists just like playlists?

![image](https://user-images.githubusercontent.com/42044258/95606361-e5003180-0a62-11eb-9b2a-04b24cc0fa2b.png)

Currently, going through chapter list with MPV is really bad. But using your menu to skip whatever chapter we want would really improve this if possible.

**Comment by jonniek** [comment]
I think it's better to make this as a separate script since it wouldn't need to use any of the playlist features. I could try implementing a simple script for this.

**Comment by CogentRedTester** [comment]
I'm actually working on a [lua module](https://github.com/CogentRedTester/mpv-scroll-list) that can be imported with the standard `require` command which should greatly simplify making these scrolling lists. This script is what inspired the basic style for it, which I've already implemented in a few of my other scripts. The pain of re-writing the same list code over and over is why I'm doing this.

The code is mostly done, I just need to properly write the documentation and perhaps change some of the variable names.

**Comment by CogentRedTester** [comment]
For example I just threw this small script together in 20 minutes:
```
local mp = require 'mp'
package.path = mp.command_native({'expand-path', '~~/scripts'}) .. '/?.lua;' .. package.path
local list = require 'scroll-list'
list.header = "Chapter List \\N ------------------------------------"

local function open_chapter()
    if list.list[list.selected] then
        mp.set_property_number('chapter', list.selected - 1)
    end
end

list.keybinds = {
    {'DOWN', 'scroll_down', function() list:scroll_down() end, {repeatable = true}},
    {'UP', 'scroll_up', function() list:scroll_up() end, {repeatable = true}},
    {'ENTER', 'open_chapter', open_chapter, {} },
    {'ESC', 'close_browser', function() list:close() end, {}}
}

mp.observe_property('chapter', 'number', function(_, curr_chapter)
    list.list = {}
    local chapter_list = mp.get_property_native('chapter-list', {})
    for i = 1, #chapter_list do
        local style = ""
        if (i-1 == curr_chapter) then 
            style = [[{\c&H33ff66&}]]
        end
        list.list[i] = {ass = style .. list.ass_escape(chapter_list[i].title)}
    end
    list:update()
end)

mp.add_key_binding("Shift+F8", "toggle-chapter-browser", function() list:toggle() end)
```

![mpv-shot0079](https://user-images.githubusercontent.com/57207260/96884138-b6557280-14c8-11eb-8476-c15928de76b4.png)

**Comment by jonniek** [comment]
I had a similar idea at one point but never finished it. Nice job with the library.

**Comment by FichteFoll** [comment]
https://github.com/darsain/uosc provides a nice menu for chapters, imo.
