### ISSUE TITLE
some ulrs can't show title name

### ISSUE THREAD

**Issue by emacs25** [donmaiq/Mpv-Playlistmanager#53]
I create m3u file with these urls :

```
#EXTM3U
#EXTINF:-1 ,Tennis prince episode 001
https://www.bilibili.com/video/av13967569/?p=1
#EXTINF:-1 ,Tennis prince episode 002
https://www.bilibili.com/video/av13967569/?p=2
#EXTINF:-1 ,Tennis prince episode 003
https://www.bilibili.com/video/av13967569/?p=3
```

and I also change playlistmanager lua with this:

```
prefer_titles = "all",
resolve_titles = true,
```
but when I play the m3u with mpv,the playlist still displays the actual urls not titles. 

I wanna know is there a way to show the playlist with the chapter names of m3u file.

**Comment by jonniek** [comment]
I failed to reproduce this issue.

`resolve_titles` doesn't affect this since the titles are embedded in the m3u file.

I can only reproduce the issue if I set `prefer_titles` to `none`. With `url` and `all` I can see the media titles as expected. So it works with the default `playlistmanager.lua` script.

Could you verify that your `prefer_titles` value is not overriden by anything. Could you also let me know your operating system and mpv version.

**Comment by emacs25** [comment]
win8. 1 32bit
mpv: 0.33.0-102-g5824d9fff8
ffmpeg: git-2021-03-16-30a69b16
from sourceforge. net

I didn't describe the matter clearly

the playlist only gets the current playing url's title without episode numbers ,but the rest urls of playlist still displays url themselves,like this below:

```
The url's title name
https://www.bilibili.com/video/av13967569/?p=2
https://www.bilibili.com/video/av13967569/?p=3
```

The first episode is playing at the moment and its title shows normally,but the rest urls still keep the same. 

so i wish to show titles using m3u file's section like "#EXTINF:-1 ,Tennis prince episode 001" to replace,like this below:

```
Tennis prince episode 001
Tennis prince episode 002
Tennis prince episode 003
```
by doing this,we can select urls conveniently and don't need to play all urls to get their titles.

**Comment by jonniek** [comment]
I understood the issue from your initial message.

For me it works as you would expect, like the second code snippet. I tested it on windows with 0.31 and 0.33 mpv versions, so I doubt it's anything related to mpv core.

The only thing that I can think of is that your `prefer_titles` setting is wrong. Could you do the following:

Add print line after the utils require around line 166
```lua
local utils = require("mp.utils")
print(utils.to_string(settings)) -- add this line
```

Then run `mpv --idle` and paste the print log here. This will print all the playlistmanager settings runtime values.

**Comment by emacs25** [comment]
I checked the option:

```
prefer_titles = "url",
```
the value is right as you say,and do you mean you can get all the url's names when using mpv to play m3u file with the "#EXTINF:-1 ," part by default? 

I find that the matter may be caused by urls. 

I test another format like this:

```
#EXTM3U
#EXTINF:-1 ,Tennis prince episode 001
https://www.bilibili.com/video/av13967567
#EXTINF:-1 ,Tennis prince episode 002
https://www.bilibili.com/video/av13967568
#EXTINF:-1 ,Tennis prince episode 003
https://www.bilibili.com/video/av13967569
```

the playlist shows m3u file the section I want. 

can you test that with these urls

```
#EXTM3U
#EXTINF:-1 ,Tennis prince episode 001
https://www.bilibili.com/video/av13967569/?p=1
#EXTINF:-1 ,Tennis prince episode 002
https://www.bilibili.com/video/av13967569/?p=2
#EXTINF:-1 ,Tennis prince episode 003
https://www.bilibili.com/video/av13967569/?p=3
```

and I think the issue will be appeared

**Comment by jonniek** [comment]
To me both playlists behave the same way. This script doesn't care about the content of the url as long as it starts with http or https protocol then it will be treated as an url.

Can you try checking the native playlist(default keybind F8) for the titles. For me it shows the titles correctly also in the native playlist. If you still cannot see the titles there, the issue must be in mpv core and not this script, in that case I suggest opening an issue in the mpv repository.

If you can see the titles correctly in the native mpv playlist, then the issue has to be on the `prefer_titles` setting, and I would like for you to confirm the runtime value by the print method I posted above. Are you using a `playlistmanager.conf` file in `script-opts` directory? If yes please paste the content here.

**Comment by emacs25** [comment]
very weird! 

the native playlist shows well too. 

there is no playlistmanager. conf in script-opts directory,and I just put lua script into portable-config/scripts directory. 

here's the output of mpv --idle:

![Uploading IMG_20210528_072322.jpg…]()

**Comment by jonniek** [comment]
That output is broken, can you paste it as text?

**Comment by emacs25** [comment]
very weird! 

the native playlist shows well too. 

there is no playlistmanager. conf in script-opts directory,and I just put lua script into portable-config/scripts directory. 

here's the output of mpv --idle:

```
D:\emacs\inbup\multimedia\mpv>mpv --idle
[playlistmanager] {"key_closeplaylist" = "q", "alphanumsort" = true, "key_movedown" = "j", "system" = "auto", "resolve_titles" = true, "playlist_sliced_prefix"= "", "filename_replace" = "", "set_title_stripped" = false, "loadfiles_filetypes" = "    [[playlistmanager]       "jpg", "jpeg", "png", "tif", "tiff", "gif", "webp", "svg", "bmp",[playlistmanager]       "mp3", "wav", "ogm", "flac", "m4a", "wma", "ogg", "opus",[playlistmanager]       "mkv", "avi", "mp4", "ogv", "webm", "rmvb", "flv", "wmv", "mpeg", "mpg", "m4v", "3gp"[playlistmanager]     ][playlistmanager]   ", "dynamic_binds" = true, "text_padding_y" = 10, "text_padding_x" = 10, "key_playfile" = "k", "playing_file" = " ▷ %name", "sync_cursor_on_load" = true, "selected_file" = " ➔ %name", "loadfiles_on_start" = false, "showamount" = 20, "prefer_titles" = "url", "playlist_sliced_suffix" = "", "playing_selected_file" = " ➤ %name", "playing_hovered_file" = " ▶ %name", "title_prefix" = "url", "sortplaylist_on_file_add" = false, "normal_file" = " ○ %name", "playlist_header" = "[%cursor/%plen]", "hovered_file" = " ● %name", "key_unselectfile" ="", "playlist_savepath" = "", "style_ass_tags" = "{\fnManaco\fs14\b0\bord1}", "key_removefile" = "BS", "key_moveup" = "l", "title_suffix" = " - mpv","loop_cursor" = true, "show_playlist_on_fileload" = 0, "open_toggles" = true, "sortplaylist_on_start" = false, "playlist_display_timeout" = 60, "scale_playlist_by_window" = true, "key_selectfile" = "RIGHT LEFT", "slice_longfilenames" = false, "slice_longfilenames_amount" = 70}
```

**Comment by emacs25** [comment]
I have no idea what happened but the title shows normally with no reasons!! 

so I close it and thank jonniek very much for help!
