### ISSUE TITLE
.zip file support

### ISSUE THREAD

**Issue by Yuki7k** [donmaiq/Mpv-Playlistmanager#55]
Hi,

So there are some issues with playlist management when loading files from within a zip. The first of which is filename displayed in the playlist is overly long and ugly.

I partially fixed this issue myself with some extrememly inelegant code for the filename_replace setting,

{"protocol":{"archive":true},"rules":[{"^%a......................................":""}]}]

Adding that and varying the amount of dots so it equals your path to your temp folder will remove the protocol and path information, e.g "archive://C:\Users...", from the playlist. It instead shows a line like example.zip|/video.mkv (you can hide the.mkv part with the rules already present in your examples).

The other significant issue is that I cannot stop jpeg or text files from loading / disaplying in the playlist if they are present within a zip I load into mpv.

The loadfiles_filetypes setting does not work when loading zips. Is it possible to alter this so I can filter what files load from within the zip?

Thank you.

**Comment by krispykiq** [comment]
Here's an alternative to the filename_replace rule you made.
```
{
        "protocol": { "archive": true},
        "rules": [
          {".+\\" : "" },
          {".+/" : ""},

        ]
      },
```

It isn't a real fix to the code but it works. 


If the archive has folders it removes them so if for some reason you want to keep it in the name.
Use these instead:
```
{".+\\" : "" },
{".+.zip|/" : ""},
```

**Comment by Yuki7k** [comment]
> Here's an alternative to the filename_replace rule you made....

Hi thanks for this! It works fantastically now! Kudos on your far better knowledge of code.

If anyone is at all curious as to why I'd want to zip up video files then the answer is windows built in file indexing. If I place a txt file within the zip with tags written in it for the video in question I can then search my collection utilizing the tags. I also place a cover jpeg or png inside the zip. In the end you get a very nice looking collection of zip files which are fully searchable (blazingly fast using windows own indexing) by the tags you've placed within them. And with mpv and QTTabBar I can then play the videos within the zip with a single key press. Very nice way to organize a video collection.

Anyways thanks very much for the nice code.

EDIT: Oh and I figured out a way to remove the jpeg and txt file from the playlist. You can use https://github.com/samhippo/mpv-scripts#clean-playlistlua , 

and replace this line

mp.register_script_message("clean-playlist", main)
with

mp.register_event("file-loaded", main)

to have it do remove them automatically.

So yeah using your snippet of code in combination with the clean-playlistlua script all the issues mentioned in my initial post are completely solved.

: )

**Comment by krispykiq** [comment]
You're welcome for the rules, I'm not really proficient at code. I was actually going to make an issue for your first problem. But I saw your initial fix, trial and errored stuff I searched up, and it worked. So thanks for the idea!

I didn't even know there were tags for windows file indexing. I learn new stuff everyday.

Congrats on finding workarounds for your issue!
