### ISSUE TITLE
Titles are lost when combining with script "reload"

### ISSUE THREAD

**Issue by KassanderN** [donmaiq/Mpv-Playlistmanager#59]
Hi. I am using the playlistmanager together with the script "reload". This makes it possible to reload a youtube file when it is stuck. However, then the titles in the playlist are replaced by the urls. I found a possibility to prevent this by altering line 312 (?) in the reload script from
  playlist[i] = mp.get_property("playlist/" .. i .. "/filename")
to
  playlist[i] = mp.get_property("playlist/" .. i .. "/title")
but then loading a different file in the playlist does not work anymore.

I don't know if you can help with that as another script is involved, but if you can I would really be happy.

Best regards

**Comment by no-realm** [comment]
@KassanderN I had the same problem when watching youtube playlists when I used the following reload script: https://github.com/4e6/mpv-reload
After looking up how the mpv included ytdl_hook loads playlists, I edited the reload script to do the same. You can find my edited version here: https://github.com/Randshot/mpv-reload/commits/ytplaylist-fix
**Use at your own discretion!**

**Comment by KassanderN** [comment]
@Randshot Yeah, it works! Thank you so much!!
