### ISSUE TITLE
Some problems about font set

### ISSUE THREAD

**Issue by kesdoputr** [donmaiq/Mpv-Playlistmanager#6]
ello,I try new version and setting up the font,here is some suggestion to compare with old version.
01.If there is a option to set that **osd not scale with windows**?
In mpv itself it has a option osd-scale-by-window=yes|no
ex.
old version with resolution 1280 and 1920(my full screen)
1280：http://i.imgur.com/CoH4mBU.jpg
1920：http://i.imgur.com/0G8voo8.jpg
osd size is the same
new version with resolution 1280 and 1920(I set font_size=8 and font family same with osd)
1280：http://i.imgur.com/Ub22vQG.jpg
1920：http://i.imgur.com/NDkNLGP.jpg
I set font to let 1920 look good,but when i switch to original size 1280,the playlist osd size is to small.
I think it's better to have a option let osd font no scale with window.

02.I think it's better to have a option to **set osd-border-size** like in mpv itself.
ex.
mpv's playlist 1920：http://i.imgur.com/V3vdGUe.jpg
old version in 1920：http://i.imgur.com/0G8voo8.jpg
new version in 1920：http://i.imgur.com/NDkNLGP.jpg

We can see that the osd-border thickness with new version is more than other two.
By the way in my mpv.conf the setting is osd-border-size=2.
Thanks for your reply^_^

PS.Maybe can let  the setting osd-scale-by-window and osd-border-size come with mpv?
Like the font famliy setting in playlistmanager(font family for playlist, empty for osd font)

**Comment by jonniek** [comment]
There is so many different ways to style the text so I made it just a ass style string like
```
{\\fnUbuntu\\fs10\\b0\\bord1} equals: font=Ubuntu, size=10, bold=no, border=1
```
There is a reference link for tags in the settings/config

I did not find a solution yet that would change ass scaling on window.

**Comment by jonniek** [comment]
Added scaling in bcb0db4604e65bea3850a6871e12e563c72b5d39

I played around with the scale percentage but it was really hard to create settings for. Now it just doesn't scale at all if disabled.

**Comment by kesdoputr** [comment]
After i set scale=false and try to setting the font
It seems all ok now,Thanks for the soon modify ^_^
