### ISSUE TITLE
Slice_longfilenames setting makes cyrillic names in the playlist half the number of characters set

### ISSUE THREAD

**Issue by yyakko** [donmaiq/Mpv-Playlistmanager#60]
This seems to happen because each cyrillic character, unlike latin, is two bytes, and the "len" function in line 332 actually counts the number of bytes, not characters.

**Comment by jonniek** [comment]
It would be trivial in Lua 5.3. Unfortunately mpv doesn't support it.

Easiest solution would probably be to rewrite this whole script in JS 🤷‍♂️
