### ISSUE TITLE
Resuming playlist

### ISSUE THREAD

**Issue by sebastian-65** [donmaiq/Mpv-Playlistmanager#62]
How can this scenario be achieved?

- play some playlist
- edit playlist (reorder, remove items)
- quit MPV
- then open that playlist again (and continue where I left off)

Thank you in advance.

**Comment by jonniek** [comment]
input.conf
`q quit-watch-later`

or 

mpv.conf
`save-position-on-quit`

Second one has the benefit of working even if player is closed from gui/other than keybind.

Edit: oh I see you re-ordered playlist. For that you need to save a new playlist. I have considered some option to override existing playlists to improve this usecase.

**Comment by sebastian-65** [comment]
Oddly, in mpv.conf `save-position-on-quit` didn't work for me for playlists (worked for single files), however `save-position-on-quit=yes` does seem to work for playlists too!

Thank you @jonniek for this wonderful playlist manager! I couldn't use MPV without it.

**Comment by jonniek** [comment]
> save-position-on-quit didn't work for me for playlists (worked for single files), however save-position-on-quit=yes

Interesting, seems like this [reddit thread](https://old.reddit.com/r/mpv/comments/ryzvvk/how_do_you_guys_continue_playing_playlist/) agrees. Maybe I have some outdated version where both work consistently. Usually if yes is omitted it should work the same as if it's defined as yes.

**Comment by sebastian-65** [comment]
Be aware, that guy posting this reddit thread is me as well :) It can be something wrong on my part, even though I don't know what.

**Comment by FichteFoll** [comment]
I haven't encountered problems with `Q quit-watch-later` outside of forgetting to close a playlist with that instead of `q` sometimes.

**Comment by RafeeDaBoy** [comment]
For me `save-position-on-quit=yes` doesn't seem to load playlist on start and `p` just pauses the video

**Comment by RafeeDaBoy** [comment]
@jonniek Is there a way to have last saved playlist autoload on next startup?

**Comment by sebastian-65** [comment]
`save-position-on-quit=yes` doesn't seem to work for me anymore, it opens playlist from position remembered in **some previous session**.  However I'm unable to figure out why it seemed worked before and what changed.

**Comment by sebastian-65** [comment]
Interesting! It works only when jumping directly from one file to the next one using "Next button" (or with hotkey `playlist-next`). This way resuming playlist will work.

However, when I jump to another file through playlist menu and hitting enter, resuming playlist won't pick up the last file. Even though I used playlist-next since then!

**Comment by jonniek** [comment]
Renaming playlist is now possible with `playlistmanager-save-interactive.lua` so original usecase can be achieved.

If there is still some bug with save position let's open another issue with reproduction steps.

**Comment by sebastian-65** [comment]
@jonniek I'm sorry for a dumb question, but how this script should be used? Is it gonna work right away when download to folder or something should be set up or be done? Thanks in advance!

Just few days ago, I wrote a python script as a workaround to save last played file to be opened again next time and it works fine but it's still a dirty hack that cannot be recommended to others.
