### ISSUE TITLE
Using mpv with this 'align right' - in this case I can't see playlist

### ISSUE THREAD

**Issue by Max-Enrik** [donmaiq/Mpv-Playlistmanager#63]
Hi,
I use mpv with following settings and in this case I can't see Playlist. I play with `text_padding_x=10 text_padding_y=30` to correct it's positions but I don't think these paddings would help me. (its hard to match correct positions).

```
osd-align-x=right
osd-align-y=bottom
```

Is there a good solution for this?

Thank you,
Max

**Comment by jonniek** [comment]
This should be fixed now 16b511060c248ebf9573da81d958c0d15a5cf5ba

Just switching the order of `ass:pos` and `ass:new_event()` seemed to fix the issue. 

Is it working as you would expect, or would you like to have an option to force it to stay in top left corner?

**Comment by Max-Enrik** [comment]
Perfect!
That is what I was looking for. Thank you so much more.

**Comment by jonniek** [comment]
I commited some unrelated debug code by mistake in above commit. Only breaks osd size if you are not using default value of scale_playlist_by_window. Anyway fixed in latest commit.
