### ISSUE TITLE
"No additional files found" - even file in the "/mpv/playlists"

### ISSUE THREAD

**Issue by Max-Enrik** [donmaiq/Mpv-Playlistmanager#64]
I made `.m3u` file by pressing `p` and I see the file in folder `%APPDATA%/mpv/playlists/` unfortunately I get message: `No additional files found`. I opened the file and I see paths of the video files in it.

Settings:
```
loadfiles_on_start=yes
playlist_savepath=
show_playlist_on_fileload=1
showamount=16
```

Any ideas?

**Comment by jonniek** [comment]
The message is related to the `loadfiles_on_start=yes` setting, it just means it didn't load any files.

Is the script behaving as you would expect, just the osd message is unexpected? If not can you elaborate a bit your issue, and what would be the expected result?

**Comment by Max-Enrik** [comment]
I need to see playlist files _(in folder `%APPDATA%/mpv/playlists/`)_ by pressing `P` over mpv player, and able to play/run it, instead of going to the folder and drag and drop it over `mpv` player to play a playlist.
I believe with that settings that I mentioned in my first comment it would do it but unfortunately so far can't make it, not possible to load the playlist file at start up, and/or maybe option to play that playlist file over `mpv` player. Is it possible to do it?

**Comment by Max-Enrik** [comment]
> The message is related to the `loadfiles_on_start=yes` setting, it just means it didn't load any files.

But I have a `.m3u` file in the `%APPDATA%/mpv/playlists/`.

**Comment by Max-Enrik** [comment]
Look like I didn't explain clearly, or maybe I didn't understand correctly.

**Comment by jonniek** [comment]
Sorry for late reply, been a bit busy lately.

I guess the issue is that m3u files are not loaded by this script. You could try adding the following to your config

```
loadfiles_filetypes=["m3u","jpg","jpeg","png","tif","tiff","gif","webp","svg","bmp","mp3","wav","ogm","flac","m4a","wma","ogg","opus","mkv","avi","mp4","ogv","webm","rmvb","flv","wmv","mpeg","mpg","m4v","3gp"]
```

**Comment by Max-Enrik** [comment]
How is it possible to keep the original **playlist** name as a **prefix**?

_Original playlist name:_
**Manufacture_Company**.m3u

_After playing the playlist name:_
**Manufacture_Company**-2023-03-23_23-23-23_playlist-size_99.m3u

**Comment by jonniek** [comment]
You can use the interactive save module https://github.com/jonniek/mpv-playlistmanager/blob/master/playlistmanager-save-interactive.lua This will extend playlistmanager to prompt for a filename when saving playlist. Unfortunately it will not know the previous name, but you can name the saved playlist with the same name to overwrite.

Another option is if you always use only one playlist then you can define the `playlist_save_filename` in playlistmanager to always override and use the same filename.
