### ISSUE TITLE
[Question] How do I make mpv to play the files in the playlist/queue only?

### ISSUE THREAD

**Issue by WhoMI7** [donmaiq/Mpv-Playlistmanager#65]
Let's say I play a file named "File 1.mkv" for example, since I'm using also using the script [autoload](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua) so the remaining files in the directory are automatically added (upto File 10.mkv) in the queue/playlist. I removed File 3, File 5, File 9, from the playlist and when the File 1(currently playing) ends it resets it to play all the files in the directory ignoring the playlist I configured. Also how do I make it to play the file in the playlist only and after the file has ended mpv should just pause? (Just like the queue has ended i.e no more files to play.

**Comment by jonniek** [comment]
You should use an autoloader that only does it once, or then by keybind. My script cannot affect what autoload script does. This script includes similar functionality, see `loadfiles(P)` in readme and/or the following config option:

```
#loadfiles at startup if there is 0 or 1 items in playlist, if 0 uses worḱing dir for files
#requires --idle=yes or --idle=once if 0 files in playlist
loadfiles_on_start=no
```

As for your last question do you mean this?
https://mpv.io/manual/master/#options-keep-open
