### ISSUE TITLE
Option request about loop

### ISSUE THREAD

**Issue by kesdoputr** [donmaiq/Mpv-Playlistmanager#7]
Hello,if this is possible that to add a option,that can let user to choose whether the playlist is loopable.
Now when i move to end it will move to first file,but i want he stop when i move to first or end of playlist.

If this option set to fause,i can press hotkey to call playlist and press
down arrow to jump to last file or files neer end quickly.A option is better
because i think someone feels the loopable playlist is better.

I think of this because i just play a playlist have 50up filess and i found the loopable playlist
is diffucult for me to jump if now i want to watch the 48th file.

 Anyway thanks for your watching

**Comment by jonniek** [comment]
Thanks for the suggestion. I think it's a great idea.

Added the feature in 79a57a212435e32c3eed19e43b3a9e61ab34c09b  
Let me know if something is still missing or if I misunderstood the feature.

**Comment by kesdoputr** [comment]
I have use try the new version,it wokrs perfect just i want.
Thanks for your quickly update.
