### ISSUE TITLE
OSD overlap

### ISSUE THREAD

**Issue by ma-zsola** [donmaiq/Mpv-Playlistmanager#74]
In my music profile there is an `osd-msg1` setting which displays some metadata about the file.
When I open the playlist manager it overlaps the OSD message.

![kép](https://user-images.githubusercontent.com/106858326/172038110-4a42cfa1-8263-4c94-9b21-4a4df4200829.png)

Is there a way to display the playlist manager right below the displayed `osd-msg1` with a small spacing, like in the case of volume control?

![kép](https://user-images.githubusercontent.com/106858326/172038131-b978a289-4f11-4e10-97ef-30abebb9b9c8.png)

The padding setting (`text_padding_y`) is not the perfect solution in my case, because the number of metadata rows varies.

Alternatively, it would be also great if `osd-msg1` would be not visible when the playlistmanager is visible

**Comment by jonniek** [comment]
I think it's not possible to see the size of other osd messages. This might have changed in recent years so maybe needs a double check.

> Alternatively, it would be also great if osd-msg1 would be not visible when the playlistmanager is visible

This sounds like a good optional setting if it's possible, or perhaps moving the osd location to bottom/right while playlist is visible.

**Comment by ma-zsola** [comment]
With my shallow scripting knowledge I think I could solve this problem. With new functions it is feasable to hide `osd-msg1` when the playlist is visible and show `osd-msg1` when the playlist is not visible:

function to hide `osd-msg1` when open the playlist:
```
function hide_osd()
  if playlist_visible then
      mp.set_property('osd-msg1', "")
  end
end
```
function to show `osd-msg1` after closing the playlist:
```
function show_osd()
  mp.set_property('osd-msg1', '${filtered-metadata}')
end
```
The `hide-osd()` function run in this section (around line 483):
```
function showplaylist(duration)
  refresh_globals()
  if plen == 0 then return end
  playlist_visible = true
  hide_osd()  -- new line
  add_keybinds()
```
The `show-osd()` function run in this section (around line 938):

```
function remove_keybinds()
  keybindstimer:kill()
  keybindstimer = mp.add_periodic_timer(settings.playlist_display_timeout, remove_keybinds)
  keybindstimer:kill()
  mp.set_osd_ass(0, 0, "")
  playlist_visible = false
  show_osd() -- new line
  if settings.dynamic_binds then
```
Unfortunately I don't know how to make this setting optional.

**Comment by jonniek** [comment]
Making it optional is just adding one if statement as a wrapper.

However, this only removes the osd when playlist is opened or visually changes. It doesn't stop new osd messages from popping up. Also it kind of conflicts with recently added osd messages for playlist actions like shuffles.

```
mp.set_property('osd-msg1', '${filtered-metadata}')
```
This assumes this is the only possible osd message which is not really true. Also if there was no osd message this would still be shown when playlist is closed.

It doesn't seem impossible to work around the above edge cases, but it's not really trivial either.

Maybe some keybinding like this could hide the osd on open
```
SHIFT+ENTER show_text "" ; script-message playlistmanager show playlist
```

**Comment by ma-zsola** [comment]
Yes, you're right.
Instead of using `osd-msg1` it would work well with `osd-level` settings 0 and 1.

**Comment by ma-zsola** [comment]
This reads out the osd-level setting and returns to its original value after closing the playlist:
```
osdlevel = mp.get_property('osd-level')

function hide_osd()
  if playlist_visible then
      mp.set_property('osd-level', 0)
  end
end

function show_osd()
  mp.set_property('osd-level', osdlevel)
end
```

**Comment by jonniek** [comment]
Seems like setting osd-level 0 doesn't reactively hide an existing osd-message.

And setting video-osd as false makes the existing osd-message stuck.

Seems like both of these are a bit unexpected behaviour. Could open an issue on mpv repo perhaps.

**Comment by ma-zsola** [comment]
I haven't found any problems using my additions with my specific mpv settings.
I managed to rewrite it to make this setting optional.
Thank you for your feedbacks and for the script.
