### ISSUE TITLE
URL Resolver Timeout Variable Duration Issue

### ISSUE THREAD

**Issue by ghost** [donmaiq/Mpv-Playlistmanager#77]
![Line 1064](https://user-images.githubusercontent.com/35814507/183530676-f151bf13-28b4-4af6-bc08-d99ea993748d.png)
On line 1064 in playlistmanager.lua there is a timeout integer used to abort the function resolving the titles within the playlist, this number is set to 5 seconds. When the function got aborted, as it did in my case I got inconsistent behaviour without any feedback. I have two cases which I ended up with, when using a larger playlist containing 32 longer URL videos no titles were displayed at all, when testing with the playlist cut down to 17 URL videos, about half of the titles loaded.

It would be great if there was a variable deciding the function timeout, slower connections or larger playlists may be affected worse, willing to wait longer than 5 seconds to fetch the metadata. A message notifying the user that all metadata could not be fetched would also be an idea, and possibly only applying a longer timeout to local playlists.

Below are two examples of behaviour I got prior to changing the integer value and after:
![Before](https://user-images.githubusercontent.com/35814507/183530675-abbabcbd-e6ac-4886-8db2-bdaaddc268fe.png)
![After](https://user-images.githubusercontent.com/35814507/183530672-e11b89a8-8561-4bd2-bdc8-c9c663b2d321.png)

Update:
There are times were you might have .m3u playlists without the EXTINF tag attached to URLs, because of something going wrong fetching titles, then this would be valid fix, for batch title resolution.
But the real fix for this was just writing the resolved URL titles to the saved playlist file using the EXTINF tag from the beginning, which it does for the title property, but not titles stored in the url_table variable containing URL link titles.

Simply adding a check for this added the EXTINF tag to URLs that are not explicitly from a youtube playlist for example (like the appendURL.lua script), where the behaviour is as expected, adding the titles to the .m3u files using the EXTINF tag.

Below is an example fixing this problem I had:
![Modification](https://user-images.githubusercontent.com/35814507/183598077-ace93bec-a9dc-416f-80a1-64690cdc1ab8.png)

**Comment by jonniek** [comment]
I added setting for timeout and increased default to 15 seconds. I also added the fallback for titles from cache when saving playlist.
