### ISSUE TITLE
Filename with Chinese characters doesn't show correctly

### ISSUE THREAD

**Issue by gitterliu** [donmaiq/Mpv-Playlistmanager#8]
1. Chinese characters filename doesn't show correctly, this is my enviroment:
    
    Microsoft Windows [版本 10.0.15063] zh-CN
    mpv 0.27.0-308-g3413fe4dfd (C) 2000-2017 mpv/MPlayer/mplayer2 projects
     built on Sat Oct 28 09:33:32 UTC 2017
    ffmpeg library versions:
       libavutil       56.0.100
       libavcodec      58.0.101
       libavformat     58.0.101
       libswscale      5.0.100
       libavfilter     7.0.100
       libswresample   3.0.100
    ffmpeg version: N-45550-g3c4c092774

    So I'm using [autload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua) for loading files. But it comes with a nother problem, some times when I jump to a file, some files in the dir will add again resulting in duplicated items. This seems a bug from autoload.ua.
    Don't know what to do now :sweat:. Would you please fix the Chinese character issue.

2. Use `mp.set_property("playlist-pos", cursor)` in function `jumptofile()` is simpler

3. Typo at line 127 `lenght`

**Comment by jonniek** [comment]
Does the chinese filenames display correctly with the native playlist view / osd? Can you give me an example of a filename that doesn't display correctly?

I cannot reproduce this bug with autoload.

2 & 3. Thanks, fixed at 8b9108ddf1a7428fa388bffb548cc6c832bcffe3

**Comment by gitterliu** [comment]
@jonniek

Here is a filename example 周杰倫 Jay Chou (特別演出 - 派偉俊)【告白氣球 Love Confession】Official MV-bu7nU9Mhpyo. Downloaded with `youtube-dl "https://www.youtube.com/watch?v=bu7nU9Mhpyo" -f worst`

1. only using playlistmanager.lua [`8b9108d`](https://github.com/jonniek/mpv-playlistmanager/commit/8b9108ddf1a7428fa388bffb548cc6c832bcffe3) and enable load files on start.
I tried again, after I chcp 65001 the issue was gone. And open from explorer with double click the select ted file's name is ok, while others are not.
In [autoload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua), it uses `mp.utils.readdir()` to get filenames, maybe you should try it.

2. Strange thing after [`8b9108d`](https://github.com/jonniek/mpv-playlistmanager/commit/8b9108ddf1a7428fa388bffb548cc6c832bcffe3), the duplicate issue is gone, now I load files with autoload.lua just like before. 
And issue closed. Thank you.
