### ISSUE TITLE
Show and move only

### ISSUE THREAD

**Issue by nobef** [donmaiq/Mpv-Playlistmanager#80]
Sorry if this is a stupid question, but I only need to show the playlist and navigate/select an item. How to properly configure the keys to disable other functions except shift / enter, top down and like that? Lua edit or need through conf? I would be glad to help, because I'm a noob

**Comment by jonniek** [comment]
hmm you used to be able to unbind keys in input.conf. Doesn't seem to work anymore.

I will change it so that all keybinds are in settings similar to the dynamic keybinds. Also I will make all the extra functionality not have a default keybind at all.
