### ISSUE TITLE
Feature request: avoid duplication in playlist

### ISSUE THREAD

**Issue by Kayizoku** [donmaiq/Mpv-Playlistmanager#81]

**Comment by Kayizoku** [comment]
a way to avoid duplication, if file exists in playlist then avoid adding it again cluttering the playlist. Only add if it does not exist

**Comment by dyphire** [comment]
dup https://github.com/jonniek/mpv-playlistmanager/issues/72

**Comment by Kayizoku** [comment]
> dup #72

Could you please tell me what I should do? I don't know which of the code does what I want

**Comment by jonniek** [comment]
Can you try the latest version on the repository if it works?

If it doesn't work can you provide some details how to reproduce the issue.
