### ISSUE TITLE
[Feature request] define loadfiles path in playlistmanager.conf

### ISSUE THREAD

**Issue by tupo2** [donmaiq/Mpv-Playlistmanager#83]
Like for the command but path defined in the playlistmanager.conf file.

**Comment by jonniek** [comment]
`input.conf`
```
SPACE script-message playlistmanager loadfiles /home/user/Videos
```

**Comment by tupo2** [comment]
> `input.conf`
> 
> ```
> SPACE script-message playlistmanager loadfiles /home/user/Videos
> ```
Works fine, thanks!
Btw, `loadfiles_filetypes` doesn't support playlist like m3u, can you add it?

**Comment by hooke007** [comment]
Hello jonniek you added double m3u in `loadfiles_filetypes` https://github.com/jonniek/mpv-playlistmanager/commit/1b2adbe5d8bc5781a46d28744f464601a5334fe3
And I don't think it's a good idea to add the playlist into it. A m3u file could contains unknown-file-types items, which may break sth.

**Comment by jonniek** [comment]
Thanks, seems like I committed a test config too by mistake. I reverted that commit.

I think maybe users can define the m3u to the setting themselves if they want it to be there.

**Comment by tupo2** [comment]
mpv support m3u, there is no reason to not add it.

> And I don't think it's a good idea to add the playlist into it. A m3u file could contains unknown-file-types items, which may break sth.

Bullshit, if a media type is not supported by mpv, it's not played, end.

**Comment by hooke007** [comment]
No one would prevent you adding it by the conf file.
And there is no reason to add the the "playlist format" into the "media types". Also a m3u file could use `txt` as extension name.

**Comment by tupo2** [comment]
It is curious that a script called **playlistmanager** should not support playlist file.
Maybe, m3u can be defined outside of `loadfiles_filetypes`.

**Comment by hooke007** [comment]
A so called playlist format could use `m3u8` `txt` `pl` or something else as extension.
And mpv could receive it without extension.

**Comment by tupo2** [comment]
Yes m3u8 should be added as well, but mpv does not recognize txt and pl:
`Failed to recognize file format.`

**Comment by hooke007** [comment]
That's the another issue. Maybe your m3u doesn't follow the rule.
It works here.
![Snipaste_2022-10-22_17-09-58](https://user-images.githubusercontent.com/41094733/197349621-6188d49c-90f9-465e-a4bf-7695728475a5.jpg)

**Comment by jonniek** [comment]
>No one would prevent you adding it by the conf file.

This

> It is curious that a script called playlistmanager should not support playlist file.

This is fair enough. But it's not a lot of effort to change the defaults. I have been thinking about some way to open saved playlists explicitly, I think that would be better. I think loadfiles will not really avoid duplicates with playlist files so it seems a bit annoying to use.
