### ISSUE TITLE
`text_padding_*` doesn't work

### ISSUE THREAD

**Issue by hooke007** [donmaiq/Mpv-Playlistmanager#86]

**Comment by jonniek** [comment]
Thanks for reporting. Seems to be broken since https://github.com/jonniek/mpv-playlistmanager/issues/63

I made a quick fix that works for top left alignment. Opening another issue for implementing it for other alignments.

**Comment by hooke007** [comment]
I am not sure what user would expect from the mpv.conf.
From my view it's safe to totally controll the style from script rather than mpv.conf. Because `osd-*` options could change the effect if some part of ones is not specified.

i.e.

`style_ass_tags = "{\\fs12\\b0\\blur0\\bord1}"`
`osd-italic=yes` force the list to be italic. Unless I set `style_ass_tags = "{\\fs12\\b0\\blur0\\bord1\\i0}"` to avoid the case.
Also i do not know how many people don't want mpv.conf to break the script-opts' preset.
