### ISSUE TITLE
[Feature request] use `start-file` event to achieve better compatibility with other scripts

### ISSUE THREAD

**Issue by dyphire** [donmaiq/Mpv-Playlistmanager#88]
Some scripts used the same event of `file-loaded` to achieve the functions about playback history. 
When this script of playlistmanager uses the `loadfiles_on_start` function, it will conflict with these scripts. Such as [history-bookmark.lua](https://github.com/yuukidach/mpv-scripts/blob/master/history-bookmark.lua).
Changing to `start-file` event will achieve better compatibility with other scripts.

**Comment by dyphire** [comment]
Now I realize that maybe this is incorrect, and use this `start-file` event has broken the behavior of `sync_cursor_on_load` option.

**Comment by jonniek** [comment]
Seems to work for me. How is it broken for you?

**Comment by dyphire** [comment]
> Seems to work for me. How is it broken for you?

Ah, This is still a issue of script behavior conflict on use same event.
When I used autoload.lua  instead of playlistmanager.lua to load files, the cursor will be positioned on the first file instead of the current file when the playlist menu is opened.
![image](https://user-images.githubusercontent.com/61936050/197829670-962bfff9-fc14-42a8-89d3-b495dc6ca4ba.png)
