### ISSUE TITLE
[Feature request] Close playlist after the last file is removed

### ISSUE THREAD

**Issue by ma-zsola** [donmaiq/Mpv-Playlistmanager#90]
I use mpv with `--idle=yes` setting.
After I remove the last file from the playlist, the last entry is still displayed for the `playlist_display_timeout` value.
I experience this when the last file is still playing, and also when the last file has already finished playing.
Is it possible to automatically close the playlist in these cases?

**Comment by jonniek** [comment]
Good idea. I noticed that the deletion of the last file is a bit delayed when in fullscreen with this change. No idea really why 🤔 

Another option without delays would be to display the playlist without any files: [0/0]
