### ISSUE TITLE
Playing a `.m3u` file results in duplicates

### ISSUE THREAD

**Issue by xfzv** [donmaiq/Mpv-Playlistmanager#92]
With `loadfiles_on_start=yes`, opening a `.m3u` file which contains all the files in the directory results in said files added twice to the playlist.

Example:

```console
tree .
.
├── 001.mkv
├── 002.mkv
└── 1.m3u
```

When opening `1.m3u`:

![image](https://user-images.githubusercontent.com/78810647/200672619-2297be1d-e67d-4cb1-9eba-f4bbac84287f.png)

Am I missing something? or maybe adding an option to exclude some file types for the `loadfiles_on_start` option?

Thanks.

**Comment by jonniek** [comment]
Thanks. That is a recent side-effect from https://github.com/jonniek/mpv-playlistmanager/issues/88 and similar issue to https://github.com/jonniek/mpv-playlistmanager/issues/89

We fixed it for opening directories, but actually playlists behave the same way as directories. I added a special case handling for `m3u` to work the same as a directory.

**Comment by xfzv** [comment]
Thank you, works just fine now.
