### ISSUE TITLE
Saving position not working when using playlist-next and playlist-prev

### ISSUE THREAD

**Issue by doesn123** [donmaiq/Mpv-Playlistmanager#95]
I'm using save-position-on-quit=yes and it is working fine when using shit+enter to switch between videos but not when using '<' and '>' to go to next and previous videos.
I've also tried the following (using o and p as keybindings which also isn't working):

p playlist-next
o playlist-prev

I'm guessing I'm missing something basic...help would be much appreciated!

**Comment by jonniek** [comment]
```
p script-message playlistmanager playlist-next
o script-message playlistmanager playlist-prev
```

`playlist-next` by itself is just a native mpv command. It's probably a bit bad naming on my part.

**Comment by doesn123** [comment]
Thanks, that now works.
However, now keepsession.lua doesn't manage to do its job of opening the last played video when mpv is launched (the beginning of the playlist is played instead), Do you know how to fix this by any chance?
